<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Idempotency Keys Table
 * ─────────────────────
 * Stores the cached JSON response for a given idempotency key
 * so that retried requests return the identical response without
 * re-processing (no double AI call, no double question_count increment).
 *
 * TTL: 5 minutes (enforced in TestController, cleaned by scheduled command).
 *
 * Phase 1 – Step 2 of PHASE_1_IMPLEMENTATION.md
 */
return new class extends Migration {
    public function up(): void
    {
        Schema::create('idempotency_keys', function (Blueprint $table) {
            $table->id();

            // The UUID v4 generated by the frontend per answer submission.
            $table->string('key', 64)->unique();

            // Full JSON-encoded HTTP response body to be replayed on duplicate requests.
            $table->text('response_json');

            // When this record becomes invalid and can be purged.
            $table->timestamp('expires_at');

            $table->timestamp('created_at')->useCurrent();

            // Index for fast purge queries (old expired records).
            $table->index('expires_at');
        });
    }

    public function down(): void
    {
        Schema::disableForeignKeyConstraints();
        Schema::dropIfExists('idempotency_keys');
        Schema::enableForeignKeyConstraints();
    }
};
