<?php

namespace Database\Seeders;

use App\Models\CareerCatalog;
use Illuminate\Database\Seeder;

/**
 * Catálogo de profesiones basado en CNO-11 (España) y ESCO,
 * con vectores RIASEC derivados de O*NET Interest Profiler.
 *
 * Cada vector RIASEC suma ~1.0 (distribución de pesos relativos).
 * Sectores: 16 categorías que cubren el mercado laboral completo.
 */
class CareerCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $careers = $this->getCareers();

        foreach ($careers as $career) {
            CareerCatalog::updateOrCreate(
                ['titulo' => $career['titulo']],
                $career
            );
        }

        $this->command->info('CareerCatalog seeded: ' . count($careers) . ' profesiones.');
    }

    private function getCareers(): array
    {
        return [
            // ══════════════════════════════════════════════
            // SECTOR 1: TECNOLOGÍA E INFORMÁTICA
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Desarrollador/a de Software',
                'codigo_cno' => '2722',
                'codigo_esco' => '2512.1',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.15,
                'riasec_i' => 0.40,
                'riasec_a' => 0.15,
                'riasec_s' => 0.05,
                'riasec_e' => 0.05,
                'riasec_c' => 0.20,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Diseña, programa y mantiene aplicaciones y sistemas informáticos que resuelven problemas reales.',
                'salidas_profesionales' => json_encode(['Full-Stack Developer', 'Backend Engineer', 'Arquitecto de Software']),
                'ruta_formativa' => 'Grado en Ingeniería Informática o FP Superior en Desarrollo de Aplicaciones → Especialización en frameworks modernos → Portfolio de proyectos',
                'habilidades_clave' => json_encode(['Pensamiento lógico', 'Resolución de problemas', 'Programación', 'Trabajo en equipo']),
                'activo' => true,
            ],
            [
                'titulo' => 'Analista de Datos',
                'codigo_cno' => '2723',
                'codigo_esco' => '2511.2',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.05,
                'riasec_i' => 0.45,
                'riasec_a' => 0.05,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.30,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Transforma grandes volúmenes de datos en información útil para la toma de decisiones estratégicas.',
                'salidas_profesionales' => json_encode(['Data Analyst', 'Business Intelligence Analyst', 'Data Engineer']),
                'ruta_formativa' => 'Grado en Estadística, Matemáticas o Informática → Máster en Big Data / Data Science → Certificaciones en herramientas (SQL, Python, Tableau)',
                'habilidades_clave' => json_encode(['Análisis estadístico', 'SQL y Python', 'Visualización de datos', 'Pensamiento crítico']),
                'activo' => true,
            ],
            [
                'titulo' => 'Técnico/a en Ciberseguridad',
                'codigo_cno' => '3821',
                'codigo_esco' => '2529.5',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.20,
                'riasec_i' => 0.35,
                'riasec_a' => 0.05,
                'riasec_s' => 0.05,
                'riasec_e' => 0.05,
                'riasec_c' => 0.30,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'emergente',
                'descripcion_corta' => 'Protege sistemas, redes y datos de organizaciones frente a ciberamenazas y ataques informáticos.',
                'salidas_profesionales' => json_encode(['Analista SOC', 'Pentester', 'Consultor de Seguridad']),
                'ruta_formativa' => 'FP Superior en Administración de Sistemas o Ciberseguridad → Certificaciones (CompTIA Security+, CEH) → Especialización en auditoría o respuesta a incidentes',
                'habilidades_clave' => json_encode(['Redes y sistemas', 'Análisis forense', 'Pensamiento analítico', 'Atención al detalle']),
                'activo' => true,
            ],
            [
                'titulo' => 'Administrador/a de Sistemas',
                'codigo_cno' => '3820',
                'codigo_esco' => '2522.1',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.30,
                'riasec_i' => 0.25,
                'riasec_a' => 0.00,
                'riasec_s' => 0.05,
                'riasec_e' => 0.05,
                'riasec_c' => 0.35,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Gestiona, configura y mantiene la infraestructura tecnológica (servidores, redes) de organizaciones.',
                'salidas_profesionales' => json_encode(['SysAdmin', 'DevOps Engineer', 'Cloud Administrator']),
                'ruta_formativa' => 'FP Superior en Administración de Sistemas Informáticos en Red → Certificaciones (Linux, AWS/Azure) → Experiencia práctica',
                'habilidades_clave' => json_encode(['Administración de servidores', 'Scripting', 'Resolución de incidencias', 'Documentación técnica']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // SECTOR 2: CIENCIA E INVESTIGACIÓN
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Biólogo/a',
                'codigo_cno' => '2411',
                'codigo_esco' => '2131.1',
                'sector' => 'Ciencia e Investigación',
                'familia_profesional' => 'Ciencias Naturales',
                'riasec_r' => 0.15,
                'riasec_i' => 0.50,
                'riasec_a' => 0.10,
                'riasec_s' => 0.10,
                'riasec_e' => 0.05,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Estudia los organismos vivos, sus funciones y relaciones con el medio ambiente para avanzar en el conocimiento científico.',
                'salidas_profesionales' => json_encode(['Investigador en laboratorio', 'Biólogo ambiental', 'Técnico en biotecnología']),
                'ruta_formativa' => 'Grado en Biología → Máster en especialidad (genética, ecología, biotecnología) → Doctorado para investigación',
                'habilidades_clave' => json_encode(['Método científico', 'Trabajo de laboratorio', 'Análisis de datos', 'Curiosidad investigadora']),
                'activo' => true,
            ],
            [
                'titulo' => 'Químico/a',
                'codigo_cno' => '2412',
                'codigo_esco' => '2113.1',
                'sector' => 'Ciencia e Investigación',
                'familia_profesional' => 'Ciencias Naturales',
                'riasec_r' => 0.20,
                'riasec_i' => 0.45,
                'riasec_a' => 0.05,
                'riasec_s' => 0.05,
                'riasec_e' => 0.05,
                'riasec_c' => 0.20,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Analiza la composición, estructura y propiedades de las sustancias, desarrollando nuevos materiales y productos.',
                'salidas_profesionales' => json_encode(['Investigador químico', 'Analista de control de calidad', 'Técnico en I+D farmacéutico']),
                'ruta_formativa' => 'Grado en Química → Máster en Química Avanzada o Investigación Química → Doctorado opcional para I+D',
                'habilidades_clave' => json_encode(['Análisis químico', 'Rigor experimental', 'Pensamiento abstracto', 'Trabajo de laboratorio']),
                'activo' => true,
            ],
            [
                'titulo' => 'Físico/a',
                'codigo_cno' => '2410',
                'codigo_esco' => '2111.1',
                'sector' => 'Ciencia e Investigación',
                'familia_profesional' => 'Ciencias Naturales',
                'riasec_r' => 0.10,
                'riasec_i' => 0.55,
                'riasec_a' => 0.10,
                'riasec_s' => 0.05,
                'riasec_e' => 0.05,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado + Máster',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Investiga las leyes fundamentales de la naturaleza, desde partículas subatómicas hasta la estructura del universo.',
                'salidas_profesionales' => json_encode(['Investigador en física', 'Físico médico', 'Consultor tecnológico']),
                'ruta_formativa' => 'Grado en Física → Máster en especialidad → Doctorado para investigación académica o aplicada',
                'habilidades_clave' => json_encode(['Modelado matemático', 'Pensamiento abstracto', 'Programación científica', 'Curiosidad intelectual']),
                'activo' => true,
            ],
            [
                'titulo' => 'Técnico/a de Laboratorio',
                'codigo_cno' => '3111',
                'codigo_esco' => '3111.1',
                'sector' => 'Ciencia e Investigación',
                'familia_profesional' => 'Sanidad / Química',
                'riasec_r' => 0.30,
                'riasec_i' => 0.35,
                'riasec_a' => 0.00,
                'riasec_s' => 0.05,
                'riasec_e' => 0.00,
                'riasec_c' => 0.30,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Realiza ensayos, análisis y pruebas en laboratorios de investigación, industria o sanidad.',
                'salidas_profesionales' => json_encode(['Técnico de laboratorio clínico', 'Analista de calidad', 'Técnico de I+D']),
                'ruta_formativa' => 'FP Superior en Laboratorio Clínico y Biomédico o Química → Prácticas en laboratorio → Especialización sectorial',
                'habilidades_clave' => json_encode(['Precisión', 'Protocolos de laboratorio', 'Instrumentación analítica', 'Rigor metodológico']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // SECTOR 3: SALUD Y BIENESTAR
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Médico/a',
                'codigo_cno' => '2111',
                'codigo_esco' => '2211.1',
                'sector' => 'Salud y Bienestar',
                'familia_profesional' => 'Sanidad',
                'riasec_r' => 0.10,
                'riasec_i' => 0.40,
                'riasec_a' => 0.05,
                'riasec_s' => 0.35,
                'riasec_e' => 0.05,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'Grado + Máster',
                'nivel_salarial' => 'Alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Diagnostica y trata enfermedades, promueve la salud y el bienestar de las personas.',
                'salidas_profesionales' => json_encode(['Médico de familia', 'Especialista hospitalario', 'Médico de urgencias']),
                'ruta_formativa' => 'Grado en Medicina (6 años) → MIR (4-5 años de especialidad) → Ejercicio profesional',
                'habilidades_clave' => json_encode(['Diagnóstico clínico', 'Empatía', 'Toma de decisiones bajo presión', 'Formación continua']),
                'activo' => true,
            ],
            [
                'titulo' => 'Enfermero/a',
                'codigo_cno' => '2121',
                'codigo_esco' => '2221.1',
                'sector' => 'Salud y Bienestar',
                'familia_profesional' => 'Sanidad',
                'riasec_r' => 0.15,
                'riasec_i' => 0.15,
                'riasec_a' => 0.05,
                'riasec_s' => 0.45,
                'riasec_e' => 0.05,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Proporciona cuidados integrales a pacientes, promueve la salud y colabora con equipos médicos multidisciplinares.',
                'salidas_profesionales' => json_encode(['Enfermero/a hospitalario', 'Enfermero/a de atención primaria', 'Enfermero/a de urgencias']),
                'ruta_formativa' => 'Grado en Enfermería (4 años) → EIR para especialidad opcional → Ejercicio profesional',
                'habilidades_clave' => json_encode(['Cuidado del paciente', 'Empatía', 'Gestión del estrés', 'Trabajo en equipo']),
                'activo' => true,
            ],
            [
                'titulo' => 'Psicólogo/a',
                'codigo_cno' => '2221',
                'codigo_esco' => '2634.1',
                'sector' => 'Salud y Bienestar',
                'familia_profesional' => 'Sanidad / Servicios Sociales',
                'riasec_r' => 0.00,
                'riasec_i' => 0.35,
                'riasec_a' => 0.10,
                'riasec_s' => 0.40,
                'riasec_e' => 0.10,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'Grado + Máster',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Estudia el comportamiento humano y ayuda a las personas a gestionar sus emociones, relaciones y salud mental.',
                'salidas_profesionales' => json_encode(['Psicólogo clínico', 'Psicólogo educativo', 'Psicólogo organizacional']),
                'ruta_formativa' => 'Grado en Psicología → Máster habilitante (PIR o Máster en Psicología General Sanitaria) → Especialización',
                'habilidades_clave' => json_encode(['Escucha activa', 'Análisis de comportamiento', 'Empatía', 'Comunicación terapéutica']),
                'activo' => true,
            ],
            [
                'titulo' => 'Fisioterapeuta',
                'codigo_cno' => '2142',
                'codigo_esco' => '2264.1',
                'sector' => 'Salud y Bienestar',
                'familia_profesional' => 'Sanidad',
                'riasec_r' => 0.30,
                'riasec_i' => 0.20,
                'riasec_a' => 0.05,
                'riasec_s' => 0.35,
                'riasec_e' => 0.05,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Rehabilita lesiones y mejora la movilidad y calidad de vida de los pacientes mediante técnicas físicas.',
                'salidas_profesionales' => json_encode(['Fisioterapeuta deportivo', 'Fisioterapeuta neurológico', 'Clínica privada']),
                'ruta_formativa' => 'Grado en Fisioterapia (4 años) → Máster en especialidad (deporte, neurología, pediátrica) → Ejercicio profesional',
                'habilidades_clave' => json_encode(['Destreza manual', 'Anatomía', 'Empatía con el paciente', 'Capacidad física']),
                'activo' => true,
            ],
            [
                'titulo' => 'Nutricionista',
                'codigo_cno' => '2295',
                'codigo_esco' => '2265.1',
                'sector' => 'Salud y Bienestar',
                'familia_profesional' => 'Sanidad',
                'riasec_r' => 0.05,
                'riasec_i' => 0.35,
                'riasec_a' => 0.05,
                'riasec_s' => 0.35,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Diseña planes de alimentación personalizados para mejorar la salud y el rendimiento de las personas.',
                'salidas_profesionales' => json_encode(['Nutricionista clínico', 'Nutricionista deportivo', 'Consultor de alimentación']),
                'ruta_formativa' => 'Grado en Nutrición Humana y Dietética → Máster en especialidad → Colegiación y consulta',
                'habilidades_clave' => json_encode(['Conocimiento nutricional', 'Comunicación', 'Planificación', 'Empatía']),
                'activo' => true,
            ],
            [
                'titulo' => 'Técnico/a en Emergencias Sanitarias',
                'codigo_cno' => '5321',
                'codigo_esco' => '3258.1',
                'sector' => 'Salud y Bienestar',
                'familia_profesional' => 'Sanidad',
                'riasec_r' => 0.35,
                'riasec_i' => 0.10,
                'riasec_a' => 0.00,
                'riasec_s' => 0.35,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'FP Medio',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Atiende situaciones de emergencia sanitaria, traslada pacientes y aplica técnicas de soporte vital.',
                'salidas_profesionales' => json_encode(['Técnico de ambulancia', 'Técnico de emergencias', 'Técnico en protección civil']),
                'ruta_formativa' => 'FP Medio en Emergencias Sanitarias (2 años) → Formación continua en SVA → Oposiciones o empresa privada',
                'habilidades_clave' => json_encode(['Reacción rápida', 'Trabajo bajo presión', 'Técnicas de soporte vital', 'Trabajo en equipo']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // SECTOR 4: EDUCACIÓN Y FORMACIÓN
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Profesor/a de Educación Primaria',
                'codigo_cno' => '2311',
                'codigo_esco' => '2341.1',
                'sector' => 'Educación y Formación',
                'familia_profesional' => 'Docencia',
                'riasec_r' => 0.05,
                'riasec_i' => 0.15,
                'riasec_a' => 0.15,
                'riasec_s' => 0.45,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Enseña y guía el aprendizaje de niños de 6 a 12 años, contribuyendo a su desarrollo integral.',
                'salidas_profesionales' => json_encode(['Maestro/a en colegio público', 'Profesor/a en centro concertado', 'Educador/a en centros especializados']),
                'ruta_formativa' => 'Grado en Educación Primaria (4 años) → Oposiciones o empleo en centros concertados/privados → Formación continua',
                'habilidades_clave' => json_encode(['Pedagogía', 'Paciencia', 'Creatividad didáctica', 'Comunicación']),
                'activo' => true,
            ],
            [
                'titulo' => 'Orientador/a Educativo',
                'codigo_cno' => '2321',
                'codigo_esco' => '2359.1',
                'sector' => 'Educación y Formación',
                'familia_profesional' => 'Docencia',
                'riasec_r' => 0.00,
                'riasec_i' => 0.25,
                'riasec_a' => 0.10,
                'riasec_s' => 0.45,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado + Máster',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Acompaña a estudiantes y familias en el proceso educativo, detectando necesidades y diseñando planes de apoyo.',
                'salidas_profesionales' => json_encode(['Orientador en instituto', 'Asesor psicopedagógico', 'Técnico en atención temprana']),
                'ruta_formativa' => 'Grado en Psicología o Pedagogía → Máster en Psicopedagogía → Oposiciones o centros privados',
                'habilidades_clave' => json_encode(['Escucha activa', 'Diagnóstico educativo', 'Empatía', 'Planificación']),
                'activo' => true,
            ],
            [
                'titulo' => 'Educador/a Infantil',
                'codigo_cno' => '2312',
                'codigo_esco' => '2342.1',
                'sector' => 'Educación y Formación',
                'familia_profesional' => 'Servicios Socioculturales y a la Comunidad',
                'riasec_r' => 0.10,
                'riasec_i' => 0.05,
                'riasec_a' => 0.20,
                'riasec_s' => 0.50,
                'riasec_e' => 0.05,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Acompaña el desarrollo de niños de 0 a 6 años en escuelas infantiles y centros de atención temprana.',
                'salidas_profesionales' => json_encode(['Educador/a en guardería', 'Técnico en atención temprana', 'Ludotecario/a']),
                'ruta_formativa' => 'FP Superior en Educación Infantil (2 años) → Prácticas en centros → Empleo público o privado',
                'habilidades_clave' => json_encode(['Paciencia', 'Creatividad lúdica', 'Comunicación con familias', 'Cuidado afectivo']),
                'activo' => true,
            ],
            [
                'titulo' => 'Formador/a de Empresa',
                'codigo_cno' => '2359',
                'codigo_esco' => '2359.2',
                'sector' => 'Educación y Formación',
                'familia_profesional' => 'Docencia',
                'riasec_r' => 0.05,
                'riasec_i' => 0.15,
                'riasec_a' => 0.10,
                'riasec_s' => 0.30,
                'riasec_e' => 0.30,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Diseña e imparte formación para empresas, desarrollando las competencias profesionales de los equipos de trabajo.',
                'salidas_profesionales' => json_encode(['Formador corporativo', 'Diseñador instruccional', 'Consultor de desarrollo de talento']),
                'ruta_formativa' => 'Grado en Pedagogía, RRHH o campo técnico → Certificado de Profesionalidad en Docencia → Experiencia en formación',
                'habilidades_clave' => json_encode(['Oratoria', 'Diseño de contenidos', 'Adaptabilidad', 'Gestión de grupos']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // SECTOR 5: ARTE, DISEÑO Y CREATIVIDAD
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Diseñador/a Gráfico',
                'codigo_cno' => '2851',
                'codigo_esco' => '2166.1',
                'sector' => 'Arte, Diseño y Creatividad',
                'familia_profesional' => 'Artes Gráficas',
                'riasec_r' => 0.10,
                'riasec_i' => 0.10,
                'riasec_a' => 0.50,
                'riasec_s' => 0.05,
                'riasec_e' => 0.15,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Crea comunicación visual a través de tipografía, imagen y composición para marcas, editoriales y medios digitales.',
                'salidas_profesionales' => json_encode(['Diseñador de identidad corporativa', 'Director de arte', 'Diseñador editorial']),
                'ruta_formativa' => 'Grado en Diseño Gráfico o Bellas Artes → Portfolio profesional → Especialización en branding, editorial o digital',
                'habilidades_clave' => json_encode(['Composición visual', 'Software de diseño', 'Creatividad', 'Tipografía']),
                'activo' => true,
            ],
            [
                'titulo' => 'Ilustrador/a',
                'codigo_cno' => '2852',
                'codigo_esco' => '2651.2',
                'sector' => 'Arte, Diseño y Creatividad',
                'familia_profesional' => 'Artes Gráficas',
                'riasec_r' => 0.15,
                'riasec_i' => 0.05,
                'riasec_a' => 0.60,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Crea imágenes, personajes y narrativas visuales para editoriales, publicidad, animación y videojuegos.',
                'salidas_profesionales' => json_encode(['Ilustrador editorial', 'Concept artist', 'Ilustrador de cómic']),
                'ruta_formativa' => 'Grado en Bellas Artes o Ilustración → Portfolio profesional → Freelance o estudio de arte',
                'habilidades_clave' => json_encode(['Dibujo', 'Narrativa visual', 'Creatividad', 'Dominio de técnicas digitales y tradicionales']),
                'activo' => true,
            ],
            [
                'titulo' => 'Fotógrafo/a Profesional',
                'codigo_cno' => '2854',
                'codigo_esco' => '3431.1',
                'sector' => 'Arte, Diseño y Creatividad',
                'familia_profesional' => 'Imagen y Sonido',
                'riasec_r' => 0.25,
                'riasec_i' => 0.10,
                'riasec_a' => 0.45,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Captura imágenes con intención artística o comercial para prensa, publicidad, eventos o proyectos personales.',
                'salidas_profesionales' => json_encode(['Fotógrafo de eventos', 'Fotoperiodista', 'Fotógrafo comercial']),
                'ruta_formativa' => 'FP Superior en Iluminación, Captación y Tratamiento de Imagen → Portfolio sólido → Especialización en sector',
                'habilidades_clave' => json_encode(['Composición fotográfica', 'Iluminación', 'Edición digital', 'Ojo artístico']),
                'activo' => true,
            ],
            [
                'titulo' => 'Músico/a Profesional',
                'codigo_cno' => '2831',
                'codigo_esco' => '2652.1',
                'sector' => 'Arte, Diseño y Creatividad',
                'familia_profesional' => 'Arte Musical',
                'riasec_r' => 0.10,
                'riasec_i' => 0.10,
                'riasec_a' => 0.55,
                'riasec_s' => 0.10,
                'riasec_e' => 0.10,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Interpreta, compone o produce música, combinando técnica instrumental con expresión artística personal.',
                'salidas_profesionales' => json_encode(['Intérprete en orquesta', 'Compositor', 'Productor musical']),
                'ruta_formativa' => 'Grado Superior en Música (Conservatorio) o Grado universitario en Musicología → Perfeccionamiento → Carrera artística',
                'habilidades_clave' => json_encode(['Técnica instrumental', 'Oído musical', 'Creatividad', 'Disciplina de práctica']),
                'activo' => true,
            ],
            [
                'titulo' => 'Diseñador/a de Interiores',
                'codigo_cno' => '2853',
                'codigo_esco' => '2161.3',
                'sector' => 'Arte, Diseño y Creatividad',
                'familia_profesional' => 'Edificación y Obra Civil',
                'riasec_r' => 0.15,
                'riasec_i' => 0.10,
                'riasec_a' => 0.45,
                'riasec_s' => 0.10,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Proyecta y transforma espacios interiores funcionales y estéticamente coherentes para viviendas, comercios y oficinas.',
                'salidas_profesionales' => json_encode(['Interiorista de viviendas', 'Diseñador de espacios comerciales', 'Home stager']),
                'ruta_formativa' => 'Grado en Diseño de Interiores o Arquitectura Interior → Portfolio de proyectos → Ejercicio libre o estudio',
                'habilidades_clave' => json_encode(['Visión espacial', 'Estética', 'Conocimiento de materiales', 'Dibujo técnico']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // SECTOR 6: COMUNICACIÓN Y MEDIOS
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Periodista',
                'codigo_cno' => '2811',
                'codigo_esco' => '2642.1',
                'sector' => 'Comunicación y Medios',
                'familia_profesional' => 'Comunicación',
                'riasec_r' => 0.05,
                'riasec_i' => 0.25,
                'riasec_a' => 0.25,
                'riasec_s' => 0.15,
                'riasec_e' => 0.20,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Investiga, redacta y comunica noticias e historias relevantes a través de prensa, radio, televisión o medios digitales.',
                'salidas_profesionales' => json_encode(['Redactor en medios', 'Periodista de investigación', 'Corresponsal']),
                'ruta_formativa' => 'Grado en Periodismo o Comunicación Audiovisual → Prácticas en medios → Especialización sectorial',
                'habilidades_clave' => json_encode(['Redacción', 'Investigación', 'Pensamiento crítico', 'Comunicación oral']),
                'activo' => true,
            ],
            [
                'titulo' => 'Realizador/a Audiovisual',
                'codigo_cno' => '2821',
                'codigo_esco' => '2654.1',
                'sector' => 'Comunicación y Medios',
                'familia_profesional' => 'Imagen y Sonido',
                'riasec_r' => 0.20,
                'riasec_i' => 0.10,
                'riasec_a' => 0.40,
                'riasec_s' => 0.05,
                'riasec_e' => 0.20,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Dirige y produce contenido audiovisual para cine, televisión, publicidad o plataformas digitales.',
                'salidas_profesionales' => json_encode(['Director de cortometrajes', 'Realizador de TV', 'Productor de contenido digital']),
                'ruta_formativa' => 'Grado en Comunicación Audiovisual o Cinematografía → Reel/Portfolio → Experiencia en producciones',
                'habilidades_clave' => json_encode(['Narrativa audiovisual', 'Dirección creativa', 'Edición de vídeo', 'Gestión de equipos']),
                'activo' => true,
            ],
            [
                'titulo' => 'Community Manager',
                'codigo_cno' => '2652',
                'codigo_esco' => '2431.3',
                'sector' => 'Comunicación y Medios',
                'familia_profesional' => 'Comercio y Marketing',
                'riasec_r' => 0.05,
                'riasec_i' => 0.10,
                'riasec_a' => 0.30,
                'riasec_s' => 0.20,
                'riasec_e' => 0.25,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Gestiona la presencia digital de marcas y empresas en redes sociales, creando contenido y comunidad.',
                'salidas_profesionales' => json_encode(['Gestor de redes sociales', 'Content creator', 'Social media strategist']),
                'ruta_formativa' => 'FP Superior en Marketing y Publicidad o Grado en Comunicación → Certificaciones en social media → Portfolio digital',
                'habilidades_clave' => json_encode(['Redacción creativa', 'Análisis de métricas', 'Creatividad visual', 'Comunicación digital']),
                'activo' => true,
            ],
            [
                'titulo' => 'Técnico/a de Sonido',
                'codigo_cno' => '3831',
                'codigo_esco' => '3521.1',
                'sector' => 'Comunicación y Medios',
                'familia_profesional' => 'Imagen y Sonido',
                'riasec_r' => 0.40,
                'riasec_i' => 0.10,
                'riasec_a' => 0.30,
                'riasec_s' => 0.05,
                'riasec_e' => 0.05,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Captura, edita y mezcla audio para producciones audiovisuales, eventos en directo y estudios de grabación.',
                'salidas_profesionales' => json_encode(['Técnico de estudio', 'Ingeniero de sonido en directo', 'Diseñador de sonido']),
                'ruta_formativa' => 'FP Superior en Sonido para Audiovisuales y Espectáculos → Prácticas en estudio → Especialización',
                'habilidades_clave' => json_encode(['Oído técnico', 'Equipos de audio', 'Edición de sonido', 'Atención al detalle']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // SECTOR 7: NEGOCIOS, FINANZAS Y DERECHO
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Abogado/a',
                'codigo_cno' => '2511',
                'codigo_esco' => '2611.1',
                'sector' => 'Negocios, Finanzas y Derecho',
                'familia_profesional' => 'Jurídica',
                'riasec_r' => 0.00,
                'riasec_i' => 0.25,
                'riasec_a' => 0.05,
                'riasec_s' => 0.15,
                'riasec_e' => 0.35,
                'riasec_c' => 0.20,
                'nivel_formacion' => 'Grado + Máster',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Asesora y defiende los derechos e intereses de personas y organizaciones ante la ley.',
                'salidas_profesionales' => json_encode(['Abogado laboralista', 'Abogado mercantil', 'Abogado penalista']),
                'ruta_formativa' => 'Grado en Derecho (4 años) → Máster de Acceso a la Abogacía → Colegiación → Especialización',
                'habilidades_clave' => json_encode(['Argumentación', 'Análisis jurídico', 'Oratoria', 'Negociación']),
                'activo' => true,
            ],
            [
                'titulo' => 'Economista',
                'codigo_cno' => '2541',
                'codigo_esco' => '2631.1',
                'sector' => 'Negocios, Finanzas y Derecho',
                'familia_profesional' => 'Administración y Gestión',
                'riasec_r' => 0.00,
                'riasec_i' => 0.35,
                'riasec_a' => 0.05,
                'riasec_s' => 0.05,
                'riasec_e' => 0.30,
                'riasec_c' => 0.25,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Analiza mercados, políticas económicas y finanzas para asesorar a empresas, gobiernos e instituciones.',
                'salidas_profesionales' => json_encode(['Analista económico', 'Consultor financiero', 'Economista en administración pública']),
                'ruta_formativa' => 'Grado en Economía → Máster en finanzas o política económica → Ejercicio profesional',
                'habilidades_clave' => json_encode(['Análisis cuantitativo', 'Pensamiento estratégico', 'Estadística', 'Comunicación de datos']),
                'activo' => true,
            ],
            [
                'titulo' => 'Técnico/a en Administración y Finanzas',
                'codigo_cno' => '3311',
                'codigo_esco' => '3313.1',
                'sector' => 'Negocios, Finanzas y Derecho',
                'familia_profesional' => 'Administración y Gestión',
                'riasec_r' => 0.00,
                'riasec_i' => 0.10,
                'riasec_a' => 0.00,
                'riasec_s' => 0.10,
                'riasec_e' => 0.25,
                'riasec_c' => 0.55,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Gestiona la contabilidad, fiscalidad y operaciones financieras de empresas y organizaciones.',
                'salidas_profesionales' => json_encode(['Contable', 'Asistente de gestión financiera', 'Técnico fiscal']),
                'ruta_formativa' => 'FP Superior en Administración y Finanzas (2 años) → Certificaciones contables → Experiencia en empresa',
                'habilidades_clave' => json_encode(['Contabilidad', 'Normativa fiscal', 'Excel avanzado', 'Organización']),
                'activo' => true,
            ],
            [
                'titulo' => 'Consultor/a de Estrategia',
                'codigo_cno' => '2551',
                'codigo_esco' => '2421.1',
                'sector' => 'Negocios, Finanzas y Derecho',
                'familia_profesional' => 'Administración y Gestión',
                'riasec_r' => 0.00,
                'riasec_i' => 0.30,
                'riasec_a' => 0.05,
                'riasec_s' => 0.10,
                'riasec_e' => 0.40,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado + Máster',
                'nivel_salarial' => 'Alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Asesora a empresas en decisiones estratégicas, optimización de procesos y transformación organizacional.',
                'salidas_profesionales' => json_encode(['Consultor en Big Four', 'Strategy Manager', 'Consultor independiente']),
                'ruta_formativa' => 'Grado en ADE, Economía o Ingeniería → MBA o Máster en consultoría → Entrar en firma de consultoría',
                'habilidades_clave' => json_encode(['Pensamiento estratégico', 'Análisis de negocio', 'Presentaciones ejecutivas', 'Resolución de problemas']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // SECTOR 8: MARKETING Y VENTAS
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Especialista en Marketing Digital',
                'codigo_cno' => '2652',
                'codigo_esco' => '2431.2',
                'sector' => 'Marketing y Ventas',
                'familia_profesional' => 'Comercio y Marketing',
                'riasec_r' => 0.05,
                'riasec_i' => 0.20,
                'riasec_a' => 0.20,
                'riasec_s' => 0.10,
                'riasec_e' => 0.35,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Planifica y ejecuta estrategias de marketing en canales digitales para captar y fidelizar clientes.',
                'salidas_profesionales' => json_encode(['SEO/SEM Manager', 'Growth hacker', 'Email marketing specialist']),
                'ruta_formativa' => 'Grado en Marketing o Comunicación → Máster en Marketing Digital → Certificaciones Google/Meta/HubSpot',
                'habilidades_clave' => json_encode(['Estrategia digital', 'Analítica web', 'Creatividad publicitaria', 'Gestión de campañas']),
                'activo' => true,
            ],
            [
                'titulo' => 'Director/a Comercial',
                'codigo_cno' => '1321',
                'codigo_esco' => '1221.1',
                'sector' => 'Marketing y Ventas',
                'familia_profesional' => 'Comercio y Marketing',
                'riasec_r' => 0.00,
                'riasec_i' => 0.10,
                'riasec_a' => 0.05,
                'riasec_s' => 0.20,
                'riasec_e' => 0.50,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Lidera equipos de ventas, define estrategias comerciales y negocia acuerdos con clientes y proveedores.',
                'salidas_profesionales' => json_encode(['Director de ventas', 'Key Account Manager', 'Business Development Manager']),
                'ruta_formativa' => 'Grado en ADE o Marketing → Experiencia en ventas B2B/B2C → Ascenso a dirección comercial',
                'habilidades_clave' => json_encode(['Negociación', 'Liderazgo', 'Orientación a resultados', 'Inteligencia emocional']),
                'activo' => true,
            ],
            [
                'titulo' => 'Técnico/a en Comercio Internacional',
                'codigo_cno' => '3511',
                'codigo_esco' => '3331.1',
                'sector' => 'Marketing y Ventas',
                'familia_profesional' => 'Comercio y Marketing',
                'riasec_r' => 0.00,
                'riasec_i' => 0.15,
                'riasec_a' => 0.00,
                'riasec_s' => 0.10,
                'riasec_e' => 0.40,
                'riasec_c' => 0.35,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Gestiona operaciones de importación y exportación, aduanas y logística internacional.',
                'salidas_profesionales' => json_encode(['Export manager', 'Agente de aduanas', 'Técnico de comercio exterior']),
                'ruta_formativa' => 'FP Superior en Comercio Internacional (2 años) → Idiomas + certificaciones → Empresa exportadora',
                'habilidades_clave' => json_encode(['Gestión aduanera', 'Idiomas', 'Negociación intercultural', 'Logística internacional']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // SECTOR 9: INDUSTRIA Y MANUFACTURA
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Ingeniero/a Industrial',
                'codigo_cno' => '2021',
                'codigo_esco' => '2141.1',
                'sector' => 'Industria y Manufactura',
                'familia_profesional' => 'Fabricación Mecánica',
                'riasec_r' => 0.30,
                'riasec_i' => 0.30,
                'riasec_a' => 0.05,
                'riasec_s' => 0.05,
                'riasec_e' => 0.15,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Diseña, optimiza y gestiona procesos productivos y sistemas industriales en sectores diversos.',
                'salidas_profesionales' => json_encode(['Ingeniero de producción', 'Ingeniero de calidad', 'Director de planta']),
                'ruta_formativa' => 'Grado en Ingeniería Industrial o Mecánica → Máster en especialización industrial → Experiencia en fábrica',
                'habilidades_clave' => json_encode(['Diseño mecánico', 'Gestión de procesos', 'CAD/CAM', 'Resolución de problemas técnicos']),
                'activo' => true,
            ],
            [
                'titulo' => 'Técnico/a en Mecatrónica',
                'codigo_cno' => '3115',
                'codigo_esco' => '3115.1',
                'sector' => 'Industria y Manufactura',
                'familia_profesional' => 'Electricidad y Electrónica',
                'riasec_r' => 0.45,
                'riasec_i' => 0.25,
                'riasec_a' => 0.05,
                'riasec_s' => 0.00,
                'riasec_e' => 0.05,
                'riasec_c' => 0.20,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Integra mecánica, electrónica, informática y automatización para diseñar y mantener sistemas industriales inteligentes.',
                'salidas_profesionales' => json_encode(['Técnico de automatización', 'Técnico de robótica industrial', 'Programador de PLC']),
                'ruta_formativa' => 'FP Superior en Mecatrónica Industrial → Formación en PLC y robótica → Carrera en industria 4.0',
                'habilidades_clave' => json_encode(['Electrónica', 'Programación industrial', 'Mecánica de precisión', 'Resolución de averías']),
                'activo' => true,
            ],
            [
                'titulo' => 'Técnico/a de Calidad',
                'codigo_cno' => '3113',
                'codigo_esco' => '3141.1',
                'sector' => 'Industria y Manufactura',
                'familia_profesional' => 'Fabricación Mecánica',
                'riasec_r' => 0.20,
                'riasec_i' => 0.20,
                'riasec_a' => 0.00,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.45,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Asegura que los productos y procesos cumplan los estándares de calidad mediante auditorías, ensayos y control estadístico.',
                'salidas_profesionales' => json_encode(['Inspector de calidad', 'Auditor ISO', 'Responsable de control de calidad']),
                'ruta_formativa' => 'FP Superior en Química Industrial o Fabricación Mecánica → Certificación ISO 9001 → Experiencia en industria',
                'habilidades_clave' => json_encode(['Atención al detalle', 'Normativa ISO', 'Metrología', 'Documentación técnica']),
                'activo' => true,
            ],
            [
                'titulo' => 'Soldador/a Industrial',
                'codigo_cno' => '7212',
                'codigo_esco' => '7212.1',
                'sector' => 'Industria y Manufactura',
                'familia_profesional' => 'Fabricación Mecánica',
                'riasec_r' => 0.60,
                'riasec_i' => 0.05,
                'riasec_a' => 0.05,
                'riasec_s' => 0.00,
                'riasec_e' => 0.00,
                'riasec_c' => 0.30,
                'nivel_formacion' => 'FP Medio',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Une estructuras metálicas con técnicas de soldadura especializada para construcción, naval, aeronáutica e industria.',
                'salidas_profesionales' => json_encode(['Soldador TIG/MIG', 'Calderero', 'Soldador de tuberías']),
                'ruta_formativa' => 'FP Medio en Soldadura y Calderería → Homologaciones de soldadura → Especialización sectorial',
                'habilidades_clave' => json_encode(['Destreza manual', 'Lectura de planos', 'Precisión', 'Resistencia física']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // SECTOR 10: CONSTRUCCIÓN, ARQUITECTURA E INGENIERÍA
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Arquitecto/a',
                'codigo_cno' => '2431',
                'codigo_esco' => '2161.1',
                'sector' => 'Construcción, Arquitectura e Ingeniería',
                'familia_profesional' => 'Edificación y Obra Civil',
                'riasec_r' => 0.15,
                'riasec_i' => 0.25,
                'riasec_a' => 0.35,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado + Máster',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Diseña edificios y espacios urbanos que equilibran funcionalidad, estética, sostenibilidad y normativa.',
                'salidas_profesionales' => json_encode(['Arquitecto proyectista', 'Urbanista', 'Arquitecto de interiores']),
                'ruta_formativa' => 'Grado en Fundamentos de Arquitectura (5 años) → Máster habilitante → Colegiación',
                'habilidades_clave' => json_encode(['Diseño espacial', 'Creatividad', 'Dibujo técnico', 'Conocimiento normativo']),
                'activo' => true,
            ],
            [
                'titulo' => 'Ingeniero/a Civil',
                'codigo_cno' => '2432',
                'codigo_esco' => '2142.1',
                'sector' => 'Construcción, Arquitectura e Ingeniería',
                'familia_profesional' => 'Edificación y Obra Civil',
                'riasec_r' => 0.30,
                'riasec_i' => 0.30,
                'riasec_a' => 0.05,
                'riasec_s' => 0.05,
                'riasec_e' => 0.15,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Diseña y supervisa la construcción de infraestructuras: puentes, carreteras, presas y edificaciones.',
                'salidas_profesionales' => json_encode(['Ingeniero de estructuras', 'Director de obra', 'Ingeniero de carreteras']),
                'ruta_formativa' => 'Grado en Ingeniería Civil (4 años) → Máster en especialidad → Colegiación → Experiencia en obra',
                'habilidades_clave' => json_encode(['Cálculo estructural', 'Gestión de obra', 'Normativa de construcción', 'Resolución técnica']),
                'activo' => true,
            ],
            [
                'titulo' => 'Topógrafo/a',
                'codigo_cno' => '3123',
                'codigo_esco' => '2165.1',
                'sector' => 'Construcción, Arquitectura e Ingeniería',
                'familia_profesional' => 'Edificación y Obra Civil',
                'riasec_r' => 0.40,
                'riasec_i' => 0.20,
                'riasec_a' => 0.00,
                'riasec_s' => 0.00,
                'riasec_e' => 0.05,
                'riasec_c' => 0.35,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Mide y representa el terreno con precisión para proyectos de construcción, catastro y cartografía.',
                'salidas_profesionales' => json_encode(['Topógrafo de obra', 'Cartógrafo', 'Técnico GIS']),
                'ruta_formativa' => 'Grado en Ingeniería Geomática y Topografía → Manejo de estaciones totales y GPS → Experiencia en campo',
                'habilidades_clave' => json_encode(['Medición de precisión', 'Instrumentos topográficos', 'GIS', 'Trabajo en exteriores']),
                'activo' => true,
            ],
            [
                'titulo' => 'Jefe/a de Obra',
                'codigo_cno' => '3121',
                'codigo_esco' => '3123.1',
                'sector' => 'Construcción, Arquitectura e Ingeniería',
                'familia_profesional' => 'Edificación y Obra Civil',
                'riasec_r' => 0.25,
                'riasec_i' => 0.10,
                'riasec_a' => 0.00,
                'riasec_s' => 0.10,
                'riasec_e' => 0.35,
                'riasec_c' => 0.20,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Coordina todos los recursos humanos, materiales y financieros necesarios para ejecutar un proyecto de construcción.',
                'salidas_profesionales' => json_encode(['Jefe de obra residencial', 'Director de proyecto de construcción', 'Project Manager']),
                'ruta_formativa' => 'Grado en Ingeniería de Edificación o Civil → Experiencia como técnico de obra → Promoción a jefatura',
                'habilidades_clave' => json_encode(['Gestión de equipos', 'Planificación', 'Control de costes', 'Conocimiento técnico de construcción']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // SECTOR 11: SERVICIOS SOCIALES Y COMUNITARIOS
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Trabajador/a Social',
                'codigo_cno' => '2811',
                'codigo_esco' => '2635.1',
                'sector' => 'Servicios Sociales y Comunitarios',
                'familia_profesional' => 'Servicios Socioculturales y a la Comunidad',
                'riasec_r' => 0.00,
                'riasec_i' => 0.10,
                'riasec_a' => 0.05,
                'riasec_s' => 0.55,
                'riasec_e' => 0.15,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Interviene con personas y comunidades en situación de vulnerabilidad para promover su bienestar e inclusión social.',
                'salidas_profesionales' => json_encode(['Trabajador social en servicios públicos', 'Técnico de intervención social', 'Coordinador de programas sociales']),
                'ruta_formativa' => 'Grado en Trabajo Social (4 años) → Colegiación → Oposiciones o empleo en ONG/administración',
                'habilidades_clave' => json_encode(['Empatía', 'Gestión de casos', 'Conocimiento legal social', 'Mediación']),
                'activo' => true,
            ],
            [
                'titulo' => 'Educador/a Social',
                'codigo_cno' => '2812',
                'codigo_esco' => '2635.2',
                'sector' => 'Servicios Sociales y Comunitarios',
                'familia_profesional' => 'Servicios Socioculturales y a la Comunidad',
                'riasec_r' => 0.05,
                'riasec_i' => 0.10,
                'riasec_a' => 0.15,
                'riasec_s' => 0.50,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Diseña e implementa programas socioeducativos para personas en riesgo de exclusión social.',
                'salidas_profesionales' => json_encode(['Educador en centros de menores', 'Dinamizador comunitario', 'Educador de calle']),
                'ruta_formativa' => 'Grado en Educación Social (4 años) → Experiencia en asociaciones o centros → Oposiciones o empleo privado',
                'habilidades_clave' => json_encode(['Acompañamiento educativo', 'Creatividad social', 'Resiliencia', 'Comunicación intercultural']),
                'activo' => true,
            ],
            [
                'titulo' => 'Integrador/a Social',
                'codigo_cno' => '3712',
                'codigo_esco' => '3412.1',
                'sector' => 'Servicios Sociales y Comunitarios',
                'familia_profesional' => 'Servicios Socioculturales y a la Comunidad',
                'riasec_r' => 0.05,
                'riasec_i' => 0.05,
                'riasec_a' => 0.05,
                'riasec_s' => 0.60,
                'riasec_e' => 0.10,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Acompaña a colectivos en riesgo de exclusión (personas con discapacidad, inmigrantes, etc.) en su proceso de integración.',
                'salidas_profesionales' => json_encode(['Integrador en centros de acogida', 'Mediador intercultural', 'Técnico de inserción laboral']),
                'ruta_formativa' => 'FP Superior en Integración Social (2 años) → Prácticas en asociaciones → Empleo en servicios sociales',
                'habilidades_clave' => json_encode(['Mediación', 'Paciencia', 'Gestión emocional', 'Conocimiento de recursos sociales']),
                'activo' => true,
            ],
            [
                'titulo' => 'Cooperante Internacional',
                'codigo_cno' => '2813',
                'codigo_esco' => '2635.3',
                'sector' => 'Servicios Sociales y Comunitarios',
                'familia_profesional' => 'Servicios Socioculturales y a la Comunidad',
                'riasec_r' => 0.10,
                'riasec_i' => 0.15,
                'riasec_a' => 0.05,
                'riasec_s' => 0.40,
                'riasec_e' => 0.20,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Trabaja en proyectos de desarrollo, ayuda humanitaria y cooperación internacional en contextos de vulnerabilidad.',
                'salidas_profesionales' => json_encode(['Técnico de cooperación en ONG', 'Coordinador de proyectos humanitarios', 'Evaluador de programas de desarrollo']),
                'ruta_formativa' => 'Grado en Trabajo Social, Relaciones Internacionales o similar → Máster en Cooperación → Experiencia en terreno',
                'habilidades_clave' => json_encode(['Adaptabilidad cultural', 'Gestión de proyectos', 'Idiomas', 'Resiliencia']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // SECTOR 12: ADMINISTRACIÓN PÚBLICA Y GESTIÓN
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Funcionario/a de Administración General',
                'codigo_cno' => '4112',
                'codigo_esco' => '3343.1',
                'sector' => 'Administración Pública y Gestión',
                'familia_profesional' => 'Administración y Gestión',
                'riasec_r' => 0.00,
                'riasec_i' => 0.10,
                'riasec_a' => 0.00,
                'riasec_s' => 0.15,
                'riasec_e' => 0.15,
                'riasec_c' => 0.60,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Gestiona trámites, expedientes y procedimientos administrativos en instituciones públicas.',
                'salidas_profesionales' => json_encode(['Auxiliar administrativo del Estado', 'Administrativo de la Seguridad Social', 'Técnico de administración local']),
                'ruta_formativa' => 'Grado universitario o FP → Preparación de oposiciones (1-3 años) → Aprobación y destino',
                'habilidades_clave' => json_encode(['Procedimiento administrativo', 'Legislación', 'Organización', 'Atención al ciudadano']),
                'activo' => true,
            ],
            [
                'titulo' => 'Técnico/a en Recursos Humanos',
                'codigo_cno' => '2423',
                'codigo_esco' => '2423.1',
                'sector' => 'Administración Pública y Gestión',
                'familia_profesional' => 'Administración y Gestión',
                'riasec_r' => 0.00,
                'riasec_i' => 0.10,
                'riasec_a' => 0.05,
                'riasec_s' => 0.30,
                'riasec_e' => 0.25,
                'riasec_c' => 0.30,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Gestiona la selección, formación, nóminas y bienestar del personal en organizaciones y empresas.',
                'salidas_profesionales' => json_encode(['Técnico de selección', 'Responsable de formación', 'HR Business Partner']),
                'ruta_formativa' => 'Grado en Relaciones Laborales, Psicología o ADE → Máster en RRHH → Prácticas en departamento de personas',
                'habilidades_clave' => json_encode(['Gestión del talento', 'Legislación laboral', 'Comunicación interpersonal', 'Empatía']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // SECTOR 13: TURISMO, HOSTELERÍA Y GASTRONOMÍA
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Chef / Cocinero/a Profesional',
                'codigo_cno' => '5011',
                'codigo_esco' => '3434.1',
                'sector' => 'Turismo, Hostelería y Gastronomía',
                'familia_profesional' => 'Hostelería y Turismo',
                'riasec_r' => 0.30,
                'riasec_i' => 0.05,
                'riasec_a' => 0.35,
                'riasec_s' => 0.10,
                'riasec_e' => 0.15,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'FP Medio',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Crea platos y menús, combina técnicas culinarias con creatividad y gestiona la cocina de establecimientos.',
                'salidas_profesionales' => json_encode(['Chef de restaurante', 'Pastelero profesional', 'Chef personal']),
                'ruta_formativa' => 'FP Medio/Superior en Cocina y Gastronomía → Prácticas en restaurantes → Especialización (repostería, cocina de autor)',
                'habilidades_clave' => json_encode(['Creatividad culinaria', 'Técnicas de cocina', 'Gestión de cocina', 'Paladar y presentación']),
                'activo' => true,
            ],
            [
                'titulo' => 'Director/a de Hotel',
                'codigo_cno' => '1411',
                'codigo_esco' => '1411.1',
                'sector' => 'Turismo, Hostelería y Gastronomía',
                'familia_profesional' => 'Hostelería y Turismo',
                'riasec_r' => 0.05,
                'riasec_i' => 0.10,
                'riasec_a' => 0.05,
                'riasec_s' => 0.20,
                'riasec_e' => 0.45,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Dirige todas las operaciones de un establecimiento hotelero: recepción, restauración, eventos y personal.',
                'salidas_profesionales' => json_encode(['Director de hotel', 'Revenue Manager', 'Director de cadena hotelera']),
                'ruta_formativa' => 'Grado en Turismo o Dirección Hotelera → Máster en Revenue Management → Experiencia progresiva en hoteles',
                'habilidades_clave' => json_encode(['Liderazgo', 'Gestión operativa', 'Idiomas', 'Orientación al cliente']),
                'activo' => true,
            ],
            [
                'titulo' => 'Guía Turístico',
                'codigo_cno' => '5113',
                'codigo_esco' => '5113.1',
                'sector' => 'Turismo, Hostelería y Gastronomía',
                'familia_profesional' => 'Hostelería y Turismo',
                'riasec_r' => 0.10,
                'riasec_i' => 0.15,
                'riasec_a' => 0.15,
                'riasec_s' => 0.35,
                'riasec_e' => 0.15,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Acompaña y explica el patrimonio cultural, histórico y natural a visitantes nacionales e internacionales.',
                'salidas_profesionales' => json_encode(['Guía de ciudad', 'Guía de naturaleza', 'Guía de museos']),
                'ruta_formativa' => 'FP Superior en Guía, Información y Asistencia Turísticas → Habilitación como guía oficial → Idiomas',
                'habilidades_clave' => json_encode(['Comunicación amena', 'Cultura general', 'Idiomas', 'Carisma y empatía']),
                'activo' => true,
            ],
            [
                'titulo' => 'Sommelier',
                'codigo_cno' => '5012',
                'codigo_esco' => '5131.2',
                'sector' => 'Turismo, Hostelería y Gastronomía',
                'familia_profesional' => 'Hostelería y Turismo',
                'riasec_r' => 0.15,
                'riasec_i' => 0.20,
                'riasec_a' => 0.25,
                'riasec_s' => 0.20,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Experto en vinos y maridaje que asesora a clientes y gestiona la carta de vinos en restaurantes de alta gama.',
                'salidas_profesionales' => json_encode(['Sommelier de restaurante', 'Asesor vinícola', 'Director de bodega']),
                'ruta_formativa' => 'Formación en enología y sumillería → Certificaciones (WSET, Court of Master Sommeliers) → Experiencia en restauración',
                'habilidades_clave' => json_encode(['Cata de vinos', 'Conocimiento enológico', 'Comunicación', 'Paladar refinado']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // SECTOR 14: DEPORTE Y ACTIVIDAD FÍSICA
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Preparador/a Físico',
                'codigo_cno' => '3720',
                'codigo_esco' => '3422.1',
                'sector' => 'Deporte y Actividad Física',
                'familia_profesional' => 'Actividades Físicas y Deportivas',
                'riasec_r' => 0.30,
                'riasec_i' => 0.15,
                'riasec_a' => 0.05,
                'riasec_s' => 0.30,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Diseña y supervisa programas de entrenamiento para deportistas profesionales o personas que buscan mejorar su condición física.',
                'salidas_profesionales' => json_encode(['Preparador físico de club deportivo', 'Personal trainer', 'Readaptador deportivo']),
                'ruta_formativa' => 'Grado en Ciencias de la Actividad Física y el Deporte → Máster en rendimiento deportivo → Colegiación',
                'habilidades_clave' => json_encode(['Fisiología del ejercicio', 'Planificación de entrenamientos', 'Motivación', 'Biomecánica']),
                'activo' => true,
            ],
            [
                'titulo' => 'Monitor/a Deportivo',
                'codigo_cno' => '3721',
                'codigo_esco' => '3422.2',
                'sector' => 'Deporte y Actividad Física',
                'familia_profesional' => 'Actividades Físicas y Deportivas',
                'riasec_r' => 0.25,
                'riasec_i' => 0.05,
                'riasec_a' => 0.10,
                'riasec_s' => 0.40,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'FP Medio',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Dirige actividades deportivas y de fitness en gimnasios, centros deportivos y campamentos.',
                'salidas_profesionales' => json_encode(['Monitor de gimnasio', 'Instructor de natación', 'Animador deportivo']),
                'ruta_formativa' => 'FP Medio en Conducción de Actividades Físico-Deportivas → Especialización en disciplina → Empleo en polideportivos',
                'habilidades_clave' => json_encode(['Condición física', 'Comunicación grupal', 'Técnica deportiva', 'Energía y motivación']),
                'activo' => true,
            ],
            [
                'titulo' => 'Gestor/a Deportivo',
                'codigo_cno' => '1431',
                'codigo_esco' => '1431.1',
                'sector' => 'Deporte y Actividad Física',
                'familia_profesional' => 'Actividades Físicas y Deportivas',
                'riasec_r' => 0.05,
                'riasec_i' => 0.10,
                'riasec_a' => 0.05,
                'riasec_s' => 0.20,
                'riasec_e' => 0.40,
                'riasec_c' => 0.20,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Planifica, organiza y dirige instalaciones y eventos deportivos, combinando gestión empresarial y pasión por el deporte.',
                'salidas_profesionales' => json_encode(['Director de instalación deportiva', 'Organizador de eventos deportivos', 'Coordinador de programas deportivos']),
                'ruta_formativa' => 'Grado en CAFYD o ADE → Máster en Gestión Deportiva → Experiencia en gestión de centros',
                'habilidades_clave' => json_encode(['Gestión de instalaciones', 'Marketing deportivo', 'Liderazgo', 'Organización de eventos']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // SECTOR 15: LOGÍSTICA Y TRANSPORTE
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Técnico/a en Logística',
                'codigo_cno' => '3521',
                'codigo_esco' => '3331.2',
                'sector' => 'Logística y Transporte',
                'familia_profesional' => 'Comercio y Marketing',
                'riasec_r' => 0.15,
                'riasec_i' => 0.10,
                'riasec_a' => 0.00,
                'riasec_s' => 0.05,
                'riasec_e' => 0.25,
                'riasec_c' => 0.45,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Coordina el almacenamiento, distribución y transporte de mercancías optimizando costes y plazos de entrega.',
                'salidas_profesionales' => json_encode(['Jefe de almacén', 'Coordinador logístico', 'Supply chain analyst']),
                'ruta_formativa' => 'FP Superior en Transporte y Logística → Certificaciones (lean logistics, SAP) → Experiencia en cadena de suministro',
                'habilidades_clave' => json_encode(['Planificación logística', 'Control de stocks', 'Sistemas ERP', 'Gestión del tiempo']),
                'activo' => true,
            ],
            [
                'titulo' => 'Controlador/a Aéreo',
                'codigo_cno' => '3154',
                'codigo_esco' => '3154.1',
                'sector' => 'Logística y Transporte',
                'familia_profesional' => 'Transporte y Mantenimiento de Vehículos',
                'riasec_r' => 0.25,
                'riasec_i' => 0.20,
                'riasec_a' => 0.00,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.40,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Dirige y asegura el tráfico aéreo en aeropuertos y rutas de vuelo, garantizando la seguridad de pasajeros y tripulaciones.',
                'salidas_profesionales' => json_encode(['Controlador de torre', 'Controlador de ruta', 'Controlador de aproximación']),
                'ruta_formativa' => 'Grado universitario + Curso de habilitación ENAIRE (2 años) → Prácticas en torre → Ejercicio profesional',
                'habilidades_clave' => json_encode(['Concentración extrema', 'Inglés avanzado', 'Toma de decisiones rápida', 'Gestión del estrés']),
                'activo' => true,
            ],
            [
                'titulo' => 'Piloto Comercial',
                'codigo_cno' => '3151',
                'codigo_esco' => '3153.1',
                'sector' => 'Logística y Transporte',
                'familia_profesional' => 'Transporte y Mantenimiento de Vehículos',
                'riasec_r' => 0.35,
                'riasec_i' => 0.15,
                'riasec_a' => 0.00,
                'riasec_s' => 0.05,
                'riasec_e' => 0.15,
                'riasec_c' => 0.30,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Opera aeronaves comerciales transportando pasajeros y mercancías con máxima seguridad y profesionalidad.',
                'salidas_profesionales' => json_encode(['Copiloto de aerolínea', 'Comandante de vuelo', 'Piloto de aviación ejecutiva']),
                'ruta_formativa' => 'ATPL (Licencia de Piloto de Transporte de Línea Aérea) → Acumulación de horas de vuelo → Contratación en aerolínea',
                'habilidades_clave' => json_encode(['Dominio técnico aeronáutico', 'Inglés avanzado', 'Trabajo bajo presión', 'Disciplina']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // SECTOR 16: AGRICULTURA, MEDIO AMBIENTE Y SOSTENIBILIDAD
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Ingeniero/a Agrónomo',
                'codigo_cno' => '2141',
                'codigo_esco' => '2132.1',
                'sector' => 'Agricultura, Medio Ambiente y Sostenibilidad',
                'familia_profesional' => 'Agraria',
                'riasec_r' => 0.35,
                'riasec_i' => 0.30,
                'riasec_a' => 0.05,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Optimiza la producción agrícola y ganadera aplicando ciencia y tecnología al sector primario.',
                'salidas_profesionales' => json_encode(['Ingeniero agrónomo', 'Técnico de riego', 'Consultor agrícola']),
                'ruta_formativa' => 'Grado en Ingeniería Agrónoma (4 años) → Colegiación → Especialización en viticultura, riego, etc.',
                'habilidades_clave' => json_encode(['Agronomía', 'Gestión de cultivos', 'Análisis de suelos', 'Tecnología agrícola']),
                'activo' => true,
            ],
            [
                'titulo' => 'Técnico/a Ambiental',
                'codigo_cno' => '2413',
                'codigo_esco' => '2133.1',
                'sector' => 'Agricultura, Medio Ambiente y Sostenibilidad',
                'familia_profesional' => 'Seguridad y Medio Ambiente',
                'riasec_r' => 0.20,
                'riasec_i' => 0.35,
                'riasec_a' => 0.05,
                'riasec_s' => 0.15,
                'riasec_e' => 0.05,
                'riasec_c' => 0.20,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Evalúa el impacto ambiental de actividades humanas y diseña planes de sostenibilidad y conservación.',
                'salidas_profesionales' => json_encode(['Consultor ambiental', 'Técnico de evaluación de impacto', 'Responsable de sostenibilidad']),
                'ruta_formativa' => 'Grado en Ciencias Ambientales → Máster en Evaluación Ambiental → Experiencia en consultora o administración',
                'habilidades_clave' => json_encode(['Legislación ambiental', 'Evaluación de impacto', 'SIG (GIS)', 'Análisis de datos ambientales']),
                'activo' => true,
            ],
            [
                'titulo' => 'Enólogo/a',
                'codigo_cno' => '2141',
                'codigo_esco' => '2145.2',
                'sector' => 'Agricultura, Medio Ambiente y Sostenibilidad',
                'familia_profesional' => 'Industrias Alimentarias',
                'riasec_r' => 0.25,
                'riasec_i' => 0.30,
                'riasec_a' => 0.15,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Dirige y controla el proceso de elaboración de vinos, desde la vendimia hasta el embotellado, combinando ciencia y arte.',
                'salidas_profesionales' => json_encode(['Enólogo de bodega', 'Director técnico de bodega', 'Asesor vinícola']),
                'ruta_formativa' => 'Grado en Enología (4 años) → Prácticas en bodegas → Ejercicio profesional en bodega o consultoría',
                'habilidades_clave' => json_encode(['Enología', 'Cata y análisis sensorial', 'Química del vino', 'Gestión de bodega']),
                'activo' => true,
            ],
            [
                'titulo' => 'Técnico/a Forestal',
                'codigo_cno' => '3142',
                'codigo_esco' => '3143.1',
                'sector' => 'Agricultura, Medio Ambiente y Sostenibilidad',
                'familia_profesional' => 'Agraria',
                'riasec_r' => 0.45,
                'riasec_i' => 0.20,
                'riasec_a' => 0.00,
                'riasec_s' => 0.05,
                'riasec_e' => 0.05,
                'riasec_c' => 0.25,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Gestiona y conserva ecosistemas forestales, previene incendios y coordina trabajos de repoblación y mantenimiento.',
                'salidas_profesionales' => json_encode(['Agente forestal', 'Técnico de prevención de incendios', 'Gestor de espacios naturales']),
                'ruta_formativa' => 'FP Superior en Gestión Forestal y del Medio Natural → Oposiciones para agente forestal o empleo privado',
                'habilidades_clave' => json_encode(['Conocimiento de ecosistemas', 'Trabajo al aire libre', 'Cartografía', 'Orientación en terreno']),
                'activo' => true,
            ],
            [
                'titulo' => 'Especialista en Energías Renovables',
                'codigo_cno' => '2151',
                'codigo_esco' => '2151.2',
                'sector' => 'Agricultura, Medio Ambiente y Sostenibilidad',
                'familia_profesional' => 'Energía y Agua',
                'riasec_r' => 0.30,
                'riasec_i' => 0.30,
                'riasec_a' => 0.05,
                'riasec_s' => 0.05,
                'riasec_e' => 0.15,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'emergente',
                'descripcion_corta' => 'Diseña, instala y gestiona sistemas de energía solar, eólica y otras fuentes renovables.',
                'salidas_profesionales' => json_encode(['Ingeniero de energía solar', 'Técnico de parque eólico', 'Consultor energético']),
                'ruta_formativa' => 'Grado en Ingeniería Energética o Eléctrica → Máster en Energías Renovables → Sector empresarial o consultoría',
                'habilidades_clave' => json_encode(['Ingeniería eléctrica', 'Diseño de instalaciones', 'Sostenibilidad', 'Normativa energética']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // PROFESIONES EMERGENTES TRANSVERSALES
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Especialista en Accesibilidad y Diseño Universal',
                'codigo_cno' => '2854',
                'codigo_esco' => '2166.4',
                'sector' => 'Servicios Sociales y Comunitarios',
                'familia_profesional' => 'Servicios Socioculturales y a la Comunidad',
                'riasec_r' => 0.10,
                'riasec_i' => 0.20,
                'riasec_a' => 0.25,
                'riasec_s' => 0.30,
                'riasec_e' => 0.10,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'emergente',
                'descripcion_corta' => 'Diseña productos, servicios y entornos accesibles para todas las personas, independientemente de sus capacidades.',
                'salidas_profesionales' => json_encode(['Consultor de accesibilidad', 'Diseñador de productos accesibles', 'Auditor de accesibilidad digital']),
                'ruta_formativa' => 'Grado en Diseño, Terapia Ocupacional o Arquitectura → Especialización en accesibilidad → Certificación',
                'habilidades_clave' => json_encode(['Empatía', 'Diseño inclusivo', 'Normativa de accesibilidad', 'Investigación con usuarios']),
                'activo' => true,
            ],
            [
                'titulo' => 'Mediador/a Cultural',
                'codigo_cno' => '2871',
                'codigo_esco' => '2636.1',
                'sector' => 'Educación y Formación',
                'familia_profesional' => 'Servicios Socioculturales y a la Comunidad',
                'riasec_r' => 0.00,
                'riasec_i' => 0.10,
                'riasec_a' => 0.25,
                'riasec_s' => 0.40,
                'riasec_e' => 0.15,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'emergente',
                'descripcion_corta' => 'Facilita el diálogo entre instituciones culturales y la sociedad, diseñando programas que acercan el arte y la cultura al público.',
                'salidas_profesionales' => json_encode(['Mediador en museos', 'Programador cultural', 'Gestor de patrimonio']),
                'ruta_formativa' => 'Grado en Historia del Arte, Humanidades o Gestión Cultural → Máster en Mediación Cultural → Prácticas en instituciones',
                'habilidades_clave' => json_encode(['Comunicación cultural', 'Gestión de públicos', 'Creatividad pedagógica', 'Conocimiento artístico']),
                'activo' => true,
            ],
            [
                'titulo' => 'Técnico/a en Prevención de Riesgos Laborales',
                'codigo_cno' => '2262',
                'codigo_esco' => '2263.1',
                'sector' => 'Industria y Manufactura',
                'familia_profesional' => 'Seguridad y Medio Ambiente',
                'riasec_r' => 0.15,
                'riasec_i' => 0.20,
                'riasec_a' => 0.00,
                'riasec_s' => 0.20,
                'riasec_e' => 0.10,
                'riasec_c' => 0.35,
                'nivel_formacion' => 'Grado + Máster',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Evalúa riesgos en entornos laborales y diseña planes de prevención para garantizar la seguridad y salud de los trabajadores.',
                'salidas_profesionales' => json_encode(['Técnico PRL en empresa', 'Auditor de seguridad laboral', 'Consultor de prevención']),
                'ruta_formativa' => 'Grado universitario → Máster en Prevención de Riesgos Laborales → Ejercicio como técnico superior en PRL',
                'habilidades_clave' => json_encode(['Evaluación de riesgos', 'Normativa de seguridad', 'Formación preventiva', 'Auditoría']),
                'activo' => true,
            ],
            [
                'titulo' => 'Veterinario/a',
                'codigo_cno' => '2151',
                'codigo_esco' => '2250.1',
                'sector' => 'Ciencia e Investigación',
                'familia_profesional' => 'Sanidad Animal',
                'riasec_r' => 0.25,
                'riasec_i' => 0.35,
                'riasec_a' => 0.00,
                'riasec_s' => 0.20,
                'riasec_e' => 0.05,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Diagnostica y trata enfermedades animales, controla la seguridad alimentaria y protege la salud pública.',
                'salidas_profesionales' => json_encode(['Veterinario clínico', 'Inspector veterinario', 'Veterinario de fauna silvestre']),
                'ruta_formativa' => 'Grado en Veterinaria (5 años) → Colegiación → Especialización clínica o pública',
                'habilidades_clave' => json_encode(['Diagnóstico clínico animal', 'Cirugía veterinaria', 'Empatía con animales y dueños', 'Ciencia biomédica']),
                'activo' => true,
            ],
            [
                'titulo' => 'Logopeda',
                'codigo_cno' => '2297',
                'codigo_esco' => '2266.1',
                'sector' => 'Salud y Bienestar',
                'familia_profesional' => 'Sanidad',
                'riasec_r' => 0.05,
                'riasec_i' => 0.25,
                'riasec_a' => 0.10,
                'riasec_s' => 0.45,
                'riasec_e' => 0.05,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Evalúa y trata trastornos de la comunicación, el lenguaje, el habla y la deglución en personas de todas las edades.',
                'salidas_profesionales' => json_encode(['Logopeda clínico', 'Logopeda escolar', 'Logopeda en centro de rehabilitación']),
                'ruta_formativa' => 'Grado en Logopedia (4 años) → Colegiación → Especialización (neurológica, infantil, voz)',
                'habilidades_clave' => json_encode(['Evaluación del lenguaje', 'Paciencia', 'Comunicación terapéutica', 'Creatividad en intervención']),
                'activo' => true,
            ],
            [
                'titulo' => 'Criminólogo/a',
                'codigo_cno' => '2619',
                'codigo_esco' => '2632.2',
                'sector' => 'Negocios, Finanzas y Derecho',
                'familia_profesional' => 'Jurídica / Seguridad',
                'riasec_r' => 0.05,
                'riasec_i' => 0.40,
                'riasec_a' => 0.05,
                'riasec_s' => 0.20,
                'riasec_e' => 0.15,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Estudia las causas del delito y diseña políticas de prevención, seguridad y reinserción social.',
                'salidas_profesionales' => json_encode(['Criminólogo forense', 'Analista de seguridad', 'Técnico de instituciones penitenciarias']),
                'ruta_formativa' => 'Grado en Criminología → Máster en análisis criminal o seguridad → Oposiciones o consultoría',
                'habilidades_clave' => json_encode(['Análisis de la conducta', 'Investigación', 'Pensamiento crítico', 'Legislación penal']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // EXPANSIÓN FASE 3: PROFESIONES EMERGENTES Y SUB-ESPECIALIDADES
            // Añadidas: Abril 2026
            // Total nuevas: +51 profesiones → Catálogo ampliado a 120
            // ══════════════════════════════════════════════
            ...NewCareersExpansion::getCareersExpansion(),
        ];
    }
}
