<?php

namespace Database\Seeders;

/**
 * Expansión del catálogo de profesiones - Fase 3
 * Añade 51 nuevas profesiones distribuidas estratégicamente.
 * 
 * Para incluir en CareerCatalogSeeder, copiar el array getCareersExpansion()
 * y añadirlo al final del array existente en getCareers().
 */
class NewCareersExpansion
{
    /**
     * Retorna las 51 nuevas profesiones para expandir el catálogo.
     */
    public static function getCareersExpansion(): array
    {
        return [
            // ══════════════════════════════════════════════
            // TECNOLOGÍA E INFORMÁTICA: +16 profesiones
            // (De 4 → 20 total en el sector)
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Ingeniero/a de IA y Machine Learning',
                'codigo_cno' => '2151',
                'codigo_esco' => '2512.3',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.10,
                'riasec_i' => 0.55,
                'riasec_a' => 0.10,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado + Máster',
                'nivel_salarial' => 'Alto',
                'tipo_profesion' => 'emergente',
                'descripcion_corta' => 'Desarrolla modelos de inteligencia artificial y algoritmos de aprendizaje automático para resolver problemas complejos.',
                'salidas_profesionales' => json_encode(['ML Engineer', 'AI Researcher', 'Data Scientist especializado en IA']),
                'ruta_formativa' => 'Grado en Matemáticas/Ingeniería Informática → Máster en IA/Data Science → Especialización en Deep Learning',
                'habilidades_clave' => json_encode(['Python', 'TensorFlow/PyTorch', 'Matemáticas avanzadas', 'Algoritmos ML']),
                'activo' => true,
            ],
            [
                'titulo' => 'Ingeniero/a DevOps / SRE',
                'codigo_cno' => '2722',
                'codigo_esco' => '2512.4',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.25,
                'riasec_i' => 0.35,
                'riasec_a' => 0.05,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.20,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Alto',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Automatiza el despliegue, monitorización y mantenimiento de infraestructura cloud y sistemas distribuidos.',
                'salidas_profesionales' => json_encode(['DevOps Engineer', 'Site Reliability Engineer', 'Cloud Infrastructure Engineer']),
                'ruta_formativa' => 'Grado en Ingeniería Informática o FP Superior DAM/ASIR → Certificaciones (AWS/Azure/Kubernetes) → Experiencia en CI/CD',
                'habilidades_clave' => json_encode(['Docker/Kubernetes', 'CI/CD', 'Cloud (AWS/Azure/GCP)', 'Scripting (Python/Bash)']),
                'activo' => true,
            ],
            [
                'titulo' => 'Diseñador/a UX/UI',
                'codigo_cno' => '2166',
                'codigo_esco' => '2166.3',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.05,
                'riasec_i' => 0.20,
                'riasec_a' => 0.50,
                'riasec_s' => 0.10,
                'riasec_e' => 0.10,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Diseña experiencias de usuario intuitivas y atractivas en aplicaciones web y móviles.',
                'salidas_profesionales' => json_encode(['UX Designer', 'UI Designer', 'Product Designer', 'UX Researcher']),
                'ruta_formativa' => 'Grado en Diseño/Comunicación Audiovisual → Bootcamp/Máster en UX/UI → Portfolio + Figma/Sketch',
                'habilidades_clave' => json_encode(['Figma/Sketch', 'Prototipado', 'Investigación de usuarios', 'Design Thinking']),
                'activo' => true,
            ],
            [
                'titulo' => 'Ingeniero/a Blockchain',
                'codigo_cno' => '2722',
                'codigo_esco' => '2512.5',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.15,
                'riasec_i' => 0.50,
                'riasec_a' => 0.10,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado + Máster',
                'nivel_salarial' => 'Alto',
                'tipo_profesion' => 'emergente',
                'descripcion_corta' => 'Desarrolla aplicaciones descentralizadas (dApps) y smart contracts en ecosistemas blockchain.',
                'salidas_profesionales' => json_encode(['Blockchain Developer', 'Smart Contract Developer', 'Web3 Engineer']),
                'ruta_formativa' => 'Grado en Ingeniería Informática → Certificaciones (Ethereum, Solidity) → Proyectos Web3',
                'habilidades_clave' => json_encode(['Solidity', 'Ethereum', 'Criptografía', 'Arquitecturas descentralizadas']),
                'activo' => true,
            ],
            [
                'titulo' => 'Ingeniero/a de Datos (Data Engineer)',
                'codigo_cno' => '2723',
                'codigo_esco' => '2511.3',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.10,
                'riasec_i' => 0.45,
                'riasec_a' => 0.05,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.25,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Alto',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Construye y mantiene pipelines de datos escalables para alimentar análisis y modelos de machine learning.',
                'salidas_profesionales' => json_encode(['Data Engineer', 'ETL Developer', 'Big Data Engineer']),
                'ruta_formativa' => 'Grado en Informática/Matemáticas → Máster en Big Data → Experiencia con Spark/Airflow',
                'habilidades_clave' => json_encode(['SQL avanzado', 'Python/Scala', 'Spark/Hadoop', 'Cloud Data Warehouses']),
                'activo' => true,
            ],
            [
                'titulo' => 'Product Manager (Tecnología)',
                'codigo_cno' => '1330',
                'codigo_esco' => '2421.3',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.05,
                'riasec_i' => 0.25,
                'riasec_a' => 0.10,
                'riasec_s' => 0.20,
                'riasec_e' => 0.30,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Alto',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Define la visión y estrategia de productos digitales, equilibrando necesidades de negocio, usuarios y tecnología.',
                'salidas_profesionales' => json_encode(['Product Manager', 'Product Owner', 'Technical Product Manager']),
                'ruta_formativa' => 'Grado en Ingeniería/ADE → Experiencia en desarrollo/startups → Certificación Product Management',
                'habilidades_clave' => json_encode(['Visión de producto', 'Metodologías Agile', 'Analítica de datos', 'Stakeholder management']),
                'activo' => true,
            ],
            [
                'titulo' => 'Ingeniero/a de Videojuegos',
                'codigo_cno' => '2722',
                'codigo_esco' => '2166.4',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Imagen y Sonido / Informática',
                'riasec_r' => 0.15,
                'riasec_i' => 0.30,
                'riasec_a' => 0.35,
                'riasec_s' => 0.05,
                'riasec_e' => 0.05,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Programa mecánicas de juego, física, IA y sistemas multiplayer para videojuegos en PC, consola y móviles.',
                'salidas_profesionales' => json_encode(['Gameplay Programmer', 'Engine Programmer', 'Technical Designer']),
                'ruta_formativa' => 'Grado en Ingeniería Informática o Desarrollo de Videojuegos → Portfolio de proyectos → Unity/Unreal Engine',
                'habilidades_clave' => json_encode(['C++/C#', 'Unity/Unreal', 'Programación de gameplay', 'Optimización de rendimiento']),
                'activo' => true,
            ],
            [
                'titulo' => 'Analista de Seguridad Informática (SOC Analyst)',
                'codigo_cno' => '3821',
                'codigo_esco' => '2529.6',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.20,
                'riasec_i' => 0.40,
                'riasec_a' => 0.05,
                'riasec_s' => 0.05,
                'riasec_e' => 0.05,
                'riasec_c' => 0.25,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'emergente',
                'descripcion_corta' => 'Monitoriza amenazas cibernéticas en tiempo real, investiga incidentes y responde a ataques informáticos.',
                'salidas_profesionales' => json_encode(['SOC Analyst', 'Incident Responder', 'Threat Hunter']),
                'ruta_formativa' => 'FP Superior en Ciberseguridad/ASIR → Certificaciones (CompTIA Security+, CEH) → Experiencia en SOC',
                'habilidades_clave' => json_encode(['SIEM', 'Análisis de logs', 'Threat Intelligence', 'Respuesta a incidentes']),
                'activo' => true,
            ],
            [
                'titulo' => 'Desarrollador/a Full-Stack',
                'codigo_cno' => '2722',
                'codigo_esco' => '2512.2',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.15,
                'riasec_i' => 0.40,
                'riasec_a' => 0.15,
                'riasec_s' => 0.05,
                'riasec_e' => 0.05,
                'riasec_c' => 0.20,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Desarrolla tanto frontend (interfaz de usuario) como backend (servidor y base de datos) de aplicaciones web.',
                'salidas_profesionales' => json_encode(['Full-Stack Developer', 'Web Developer', 'Software Engineer']),
                'ruta_formativa' => 'FP Superior DAW/DAM → Bootcamp de desarrollo → Portfolio de proyectos reales',
                'habilidades_clave' => json_encode(['JavaScript', 'React/Vue/Angular', 'Node.js/Python/PHP', 'Bases de datos']),
                'activo' => true,
            ],
            [
                'titulo' => 'Arquitecto/a Cloud',
                'codigo_cno' => '2722',
                'codigo_esco' => '2512.6',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.20,
                'riasec_i' => 0.40,
                'riasec_a' => 0.05,
                'riasec_s' => 0.05,
                'riasec_e' => 0.15,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado + Máster',
                'nivel_salarial' => 'Alto',
                'tipo_profesion' => 'emergente',
                'descripcion_corta' => 'Diseña infraestructuras cloud escalables, seguras y cost-efficient para empresas que migran a la nube.',
                'salidas_profesionales' => json_encode(['Cloud Architect', 'Solutions Architect', 'Cloud Consultant']),
                'ruta_formativa' => 'Grado en Ingeniería Informática → Certificaciones (AWS Solutions Architect, Azure Architect) → Experiencia enterprise',
                'habilidades_clave' => json_encode(['AWS/Azure/GCP', 'Arquitecturas distribuidas', 'Redes y seguridad', 'FinOps']),
                'activo' => true,
            ],
            [
                'titulo' => 'QA Engineer / Tester de Software',
                'codigo_cno' => '3822',
                'codigo_esco' => '2512.7',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.15,
                'riasec_i' => 0.30,
                'riasec_a' => 0.05,
                'riasec_s' => 0.05,
                'riasec_e' => 0.05,
                'riasec_c' => 0.40,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Asegura la calidad del software mediante pruebas manuales y automatizadas antes de su lanzamiento.',
                'salidas_profesionales' => json_encode(['QA Manual Tester', 'QA Automation Engineer', 'Test Manager']),
                'ruta_formativa' => 'FP Superior DAM/DAW → Certificación ISTQB → Experiencia con herramientas de testing (Selenium, Cypress)',
                'habilidades_clave' => json_encode(['Testing manual y automatizado', 'Selenium/Cypress', 'Metodologías Agile', 'Atención al detalle']),
                'activo' => true,
            ],
            [
                'titulo' => 'Especialista en Internet de las Cosas (IoT)',
                'codigo_cno' => '2722',
                'codigo_esco' => '2529.7',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Electricidad y Electrónica / Informática',
                'riasec_r' => 0.30,
                'riasec_i' => 0.35,
                'riasec_a' => 0.05,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'emergente',
                'descripcion_corta' => 'Desarrolla sistemas que conectan dispositivos físicos a internet para smart homes, wearables e industria 4.0.',
                'salidas_profesionales' => json_encode(['IoT Developer', 'Embedded Systems Engineer', 'Smart Devices Engineer']),
                'ruta_formativa' => 'Grado en Ingeniería Informática/Electrónica → Especialización en IoT → Proyectos con Arduino/Raspberry Pi',
                'habilidades_clave' => json_encode(['Programación embebida', 'Protocolos IoT (MQTT, CoAP)', 'Arduino/Raspberry Pi', 'Cloud IoT']),
                'activo' => true,
            ],
            [
                'titulo' => 'Desarrollador/a de Realidad Virtual/Aumentada',
                'codigo_cno' => '2722',
                'codigo_esco' => '2166.5',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Imagen y Sonido / Informática',
                'riasec_r' => 0.15,
                'riasec_i' => 0.30,
                'riasec_a' => 0.35,
                'riasec_s' => 0.05,
                'riasec_e' => 0.05,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'emergente',
                'descripcion_corta' => 'Crea experiencias inmersivas en VR/AR para gaming, formación, marketing y simulación médica.',
                'salidas_profesionales' => json_encode(['VR Developer', 'AR Developer', 'XR Engineer']),
                'ruta_formativa' => 'Grado en Ingeniería Informática o Desarrollo de Videojuegos → Especialización VR/AR → Unity/Unreal + Oculus SDK',
                'habilidades_clave' => json_encode(['Unity/Unreal', 'C#/C++', '3D programming', 'UX en espacios 3D']),
                'activo' => true,
            ],
            [
                'titulo' => 'Especialista en Automatización (RPA Developer)',
                'codigo_cno' => '2722',
                'codigo_esco' => '2512.8',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.20,
                'riasec_i' => 0.35,
                'riasec_a' => 0.05,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.25,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Automatiza procesos empresariales repetitivos mediante robots de software (RPA) para mejorar eficiencia.',
                'salidas_profesionales' => json_encode(['RPA Developer', 'Automation Consultant', 'Process Automation Engineer']),
                'ruta_formativa' => 'FP Superior DAM/ASIR → Certificaciones (UiPath, Automation Anywhere) → Experiencia en automatización',
                'habilidades_clave' => json_encode(['UiPath/Automation Anywhere', 'Python', 'Análisis de procesos', 'Scripting']),
                'activo' => true,
            ],
            [
                'titulo' => 'Ingeniero/a de Robótica',
                'codigo_cno' => '2151',
                'codigo_esco' => '2144.1',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Electricidad y Electrónica',
                'riasec_r' => 0.35,
                'riasec_i' => 0.40,
                'riasec_a' => 0.05,
                'riasec_s' => 0.00,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado + Máster',
                'nivel_salarial' => 'Alto',
                'tipo_profesion' => 'emergente',
                'descripcion_corta' => 'Diseña, programa y mantiene robots industriales, médicos y de servicio para automatización avanzada.',
                'salidas_profesionales' => json_encode(['Ingeniero de robótica industrial', 'Desarrollador de robots autónomos', 'Ingeniero de sistemas robóticos']),
                'ruta_formativa' => 'Grado en Ingeniería Robótica/Mecatrónica → Máster en Robótica → ROS y control de robots',
                'habilidades_clave' => json_encode(['ROS (Robot Operating System)', 'Programación de control', 'Visión artificial', 'Mecánica y electrónica']),
                'activo' => true,
            ],
            [
                'titulo' => 'Consultor/a de Transformación Digital',
                'codigo_cno' => '2551',
                'codigo_esco' => '2421.4',
                'sector' => 'Tecnología e Informática',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.05,
                'riasec_i' => 0.30,
                'riasec_a' => 0.05,
                'riasec_s' => 0.15,
                'riasec_e' => 0.35,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado + Máster',
                'nivel_salarial' => 'Alto',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Asesora a empresas en su transición hacia modelos digitales, optimizando procesos con tecnología.',
                'salidas_profesionales' => json_encode(['Digital Transformation Consultant', 'Change Manager', 'IT Strategy Consultant']),
                'ruta_formativa' => 'Grado en ADE/Ingeniería → MBA o Máster en Transformación Digital → Experiencia en consultora',
                'habilidades_clave' => json_encode(['Estrategia digital', 'Change management', 'Gestión de proyectos', 'Conocimiento de tecnologías emergentes']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // SALUD Y BIENESTAR: +10 profesiones
            // (De 7 → 17 total)
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Nutricionista Deportivo/a',
                'codigo_cno' => '2295',
                'codigo_esco' => '2265.2',
                'sector' => 'Salud y Bienestar',
                'familia_profesional' => 'Sanidad',
                'riasec_r' => 0.05,
                'riasec_i' => 0.30,
                'riasec_a' => 0.05,
                'riasec_s' => 0.40,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado + Máster',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Optimiza el rendimiento de deportistas mediante planes nutricionales personalizados según su disciplina.',
                'salidas_profesionales' => json_encode(['Nutricionista de equipos deportivos', 'Consultor nutricional para atletas', 'Investigador en nutrición deportiva']),
                'ruta_formativa' => 'Grado en Nutrición y Dietética → Máster en Nutrición Deportiva → Certificaciones (ISSN) → Experiencia con deportistas',
                'habilidades_clave' => json_encode(['Metabolismo deportivo', 'Suplementación', 'Planificación nutricional', 'Fisiología del ejercicio']),
                'activo' => true,
            ],
            [
                'titulo' => 'Terapeuta Ocupacional',
                'codigo_cno' => '2262',
                'codigo_esco' => '2269.1',
                'sector' => 'Salud y Bienestar',
                'familia_profesional' => 'Sanidad',
                'riasec_r' => 0.15,
                'riasec_i' => 0.20,
                'riasec_a' => 0.10,
                'riasec_s' => 0.40,
                'riasec_e' => 0.05,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Ayuda a personas con discapacidades físicas, mentales o sociales a realizar actividades de la vida diaria.',
                'salidas_profesionales' => json_encode(['Terapeuta en rehabilitación', 'TO pediátrico', 'TO en salud mental']),
                'ruta_formativa' => 'Grado en Terapia Ocupacional (4 años) → Colegiación → Especialización por área clínica',
                'habilidades_clave' => json_encode(['Evaluación funcional', 'Adaptación del entorno', 'Empatía', 'Creatividad terapéutica']),
                'activo' => true,
            ],
            [
                'titulo' => 'Podólogo/a',
                'codigo_cno' => '2262',
                'codigo_esco' => '2269.2',
                'sector' => 'Salud y Bienestar',
                'familia_profesional' => 'Sanidad',
                'riasec_r' => 0.25,
                'riasec_i' => 0.20,
                'riasec_a' => 0.00,
                'riasec_s' => 0.40,
                'riasec_e' => 0.05,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Diagnostica y trata afecciones del pie y tobillo, desde uñas encarnadas hasta biomecánica de la marcha.',
                'salidas_profesionales' => json_encode(['Podólogo clínico', 'Podólogo deportivo', 'Podólogo infantil']),
                'ruta_formativa' => 'Grado en Podología (4 años) → Colegiación → Clínica propia o empleo en centros sanitarios',
                'habilidades_clave' => json_encode(['Biomecánica del pie', 'Quiropodología', 'Ortopodología', 'Atención al paciente']),
                'activo' => true,
            ],
            [
                'titulo' => 'Optometrista',
                'codigo_cno' => '2262',
                'codigo_esco' => '2267.1',
                'sector' => 'Salud y Bienestar',
                'familia_profesional' => 'Sanidad',
                'riasec_r' => 0.20,
                'riasec_i' => 0.30,
                'riasec_a' => 0.00,
                'riasec_s' => 0.35,
                'riasec_e' => 0.05,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Evalúa la visión, prescribe lentes correctoras y detecta problemas oculares que requieren derivación médica.',
                'salidas_profesionales' => json_encode(['Optometrista en óptica', 'Contactólogo', 'Optometrista en clínica oftalmológica']),
                'ruta_formativa' => 'Grado en Óptica y Optometría (4 años) → Colegiación → Especialización en lentes de contacto/baja visión',
                'habilidades_clave' => json_encode(['Refracción', 'Optometría clínica', 'Adaptación de lentes de contacto', 'Instrumentación óptica']),
                'activo' => true,
            ],
            [
                'titulo' => 'Farmacéutico/a',
                'codigo_cno' => '2262',
                'codigo_esco' => '2262.1',
                'sector' => 'Salud y Bienestar',
                'familia_profesional' => 'Sanidad',
                'riasec_r' => 0.10,
                'riasec_i' => 0.35,
                'riasec_a' => 0.00,
                'riasec_s' => 0.35,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Dispensa medicamentos, asesora sobre su uso correcto y participa en la investigación farmacéutica.',
                'salidas_profesionales' => json_encode(['Farmacéutico comunitario', 'Farmacéutico hospitalario', 'Investigador farmacéutico']),
                'ruta_formativa' => 'Grado en Farmacia (5 años) → FIR para especialidad hospitalaria → Colegiación → Ejercicio o investigación',
                'habilidades_clave' => json_encode(['Farmacología', 'Atención farmacéutica', 'Química farmacéutica', 'Comunicación sanitaria']),
                'activo' => true,
            ],
            [
                'titulo' => 'Técnico/a en Radioterapia',
                'codigo_cno' => '3211',
                'codigo_esco' => '3211.2',
                'sector' => 'Salud y Bienestar',
                'familia_profesional' => 'Sanidad',
                'riasec_r' => 0.30,
                'riasec_i' => 0.20,
                'riasec_a' => 0.00,
                'riasec_s' => 0.30,
                'riasec_e' => 0.00,
                'riasec_c' => 0.20,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Aplica tratamientos de radioterapia a pacientes oncológicos bajo supervisión médica.',
                'salidas_profesionales' => json_encode(['Técnico en radioterapia hospitalaria', 'Técnico en braquiterapia', 'Técnico en radiofísica']),
                'ruta_formativa' => 'FP Superior en Radioterapia y Dosimetría (2 años) → Prácticas en hospital → Oposiciones o empleo privado',
                'habilidades_clave' => json_encode(['Manejo de aceleradores lineales', 'Protección radiológica', 'Atención al paciente oncológico', 'Dosimetría']),
                'activo' => true,
            ],
            [
                'titulo' => 'Técnico/a de Laboratorio Clínico',
                'codigo_cno' => '3211',
                'codigo_esco' => '3212.1',
                'sector' => 'Salud y Bienestar',
                'familia_profesional' => 'Sanidad',
                'riasec_r' => 0.30,
                'riasec_i' => 0.30,
                'riasec_a' => 0.00,
                'riasec_s' => 0.10,
                'riasec_e' => 0.00,
                'riasec_c' => 0.30,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Realiza análisis clínicos (sangre, orina, tejidos) para el diagnóstico y seguimiento de enfermedades.',
                'salidas_profesionales' => json_encode(['Técnico en laboratorio hospitalario', 'Técnico en laboratorio privado', 'Técnico en banco de sangre']),
                'ruta_formativa' => 'FP Superior en Laboratorio Clínico y Biomédico (2 años) → Prácticas → Oposiciones o sector privado',
                'habilidades_clave' => json_encode(['Técnicas de análisis clínico', 'Manejo de autoanalizadores', 'Bioseguridad', 'Precisión y rigor']),
                'activo' => true,
            ],
            [
                'titulo' => 'Higienista Dental',
                'codigo_cno' => '3251',
                'codigo_esco' => '3251.1',
                'sector' => 'Salud y Bienestar',
                'familia_profesional' => 'Sanidad',
                'riasec_r' => 0.25,
                'riasec_i' => 0.15,
                'riasec_a' => 0.00,
                'riasec_s' => 0.40,
                'riasec_e' => 0.05,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Realiza limpiezas dentales, aplica tratamientos preventivos y educa en salud bucodental.',
                'salidas_profesionales' => json_encode(['Higienista en clínica dental', 'Higienista en salud pública', 'Educador en salud bucodental']),
                'ruta_formativa' => 'FP Superior en Higiene Bucodental (2 años) → Prácticas en clínica → Empleo en clínicas dentales',
                'habilidades_clave' => json_encode(['Técnicas de higiene bucodental', 'Manejo de instrumental', 'Educación sanitaria', 'Trato con pacientes']),
                'activo' => true,
            ],
            [
                'titulo' => 'Auxiliar de Veterinaria',
                'codigo_cno' => '3240',
                'codigo_esco' => '3240.1',
                'sector' => 'Salud y Bienestar',
                'familia_profesional' => 'Sanidad',
                'riasec_r' => 0.30,
                'riasec_i' => 0.10,
                'riasec_a' => 0.00,
                'riasec_s' => 0.40,
                'riasec_e' => 0.05,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'FP Medio',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Asiste al veterinario en consultas, cirugías y hospitalización de animales de compañía y exóticos.',
                'salidas_profesionales' => json_encode(['Auxiliar en clínica veterinaria', 'Auxiliar en hospitalización', 'Peluquería canina']),
                'ruta_formativa' => 'FP Medio en Cuidados Auxiliares de Enfermería (adaptado) → Curso de Auxiliar de Veterinaria → Prácticas en clínica',
                'habilidades_clave' => json_encode(['Manejo de animales', 'Asistencia veterinaria', 'Limpieza y esterilización', 'Empatía con animales']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // ARTE, DISEÑO Y CREATIVIDAD: +10 profesiones
            // (De 5 → 15 total)
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Diseñador/a de Moda',
                'codigo_cno' => '2852',
                'codigo_esco' => '2163.1',
                'sector' => 'Arte, Diseño y Creatividad',
                'familia_profesional' => 'Textil, Confección y Piel',
                'riasec_r' => 0.10,
                'riasec_i' => 0.10,
                'riasec_a' => 0.55,
                'riasec_s' => 0.05,
                'riasec_e' => 0.15,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Crea prendas y colecciones de moda combinando creatividad, tendencias y conocimiento técnico textil.',
                'salidas_profesionales' => json_encode(['Diseñador de alta costura', 'Diseñador de prêt-à-porter', 'Diseñador de complementos']),
                'ruta_formativa' => 'Grado en Diseño de Moda → Portfolio profesional → Prácticas en firmas de moda → Marca propia o freelance',
                'habilidades_clave' => json_encode(['Patronaje', 'Ilustración de moda', 'Conocimiento de tejidos', 'Tendencias y estilo']),
                'activo' => true,
            ],
            [
                'titulo' => 'Animador/a 3D',
                'codigo_cno' => '2852',
                'codigo_esco' => '2166.2',
                'sector' => 'Arte, Diseño y Creatividad',
                'familia_profesional' => 'Imagen y Sonido',
                'riasec_r' => 0.15,
                'riasec_i' => 0.15,
                'riasec_a' => 0.50,
                'riasec_s' => 0.05,
                'riasec_e' => 0.05,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Da vida a personajes y objetos 3D para cine, videojuegos, publicidad y arquitectura virtual.',
                'salidas_profesionales' => json_encode(['Animador en estudio de cine', 'Animador de videojuegos', 'Motion graphics artist']),
                'ruta_formativa' => 'FP Superior en Animaciones 3D → Reel profesional → Dominio de Maya/Blender/3ds Max → Portfolio',
                'habilidades_clave' => json_encode(['Maya/Blender/3ds Max', 'Rigging', 'Animación de personajes', 'Motion graphics']),
                'activo' => true,
            ],
            [
                'titulo' => 'Motion Designer',
                'codigo_cno' => '2166',
                'codigo_esco' => '2166.6',
                'sector' => 'Arte, Diseño y Creatividad',
                'familia_profesional' => 'Imagen y Sonido',
                'riasec_r' => 0.10,
                'riasec_i' => 0.15,
                'riasec_a' => 0.50,
                'riasec_s' => 0.05,
                'riasec_e' => 0.15,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'emergente',
                'descripcion_corta' => 'Crea gráficos animados para branding, publicidad, vídeo corporativo y contenido digital.',
                'salidas_profesionales' => json_encode(['Motion designer en agencia', 'Freelance motion graphics', 'Video editor creativo']),
                'ruta_formativa' => 'Grado en Diseño Gráfico/Audiovisual → Especialización en After Effects → Reel de proyectos',
                'habilidades_clave' => json_encode(['After Effects', 'Cinema 4D', 'Diseño gráfico', 'Timing y ritmo visual']),
                'activo' => true,
            ],
            [
                'titulo' => 'Diseñador/a de Videojuegos (Game Designer)',
                'codigo_cno' => '2166',
                'codigo_esco' => '2166.7',
                'sector' => 'Arte, Diseño y Creatividad',
                'familia_profesional' => 'Imagen y Sonido',
                'riasec_r' => 0.10,
                'riasec_i' => 0.20,
                'riasec_a' => 0.45,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Define las mecánicas, progresión, narrativa y experiencia de juego de videojuegos.',
                'salidas_profesionales' => json_encode(['Game Designer', 'Narrative Designer', 'Level Designer']),
                'ruta_formativa' => 'Grado en Desarrollo de Videojuegos/Diseño → Portfolio de juegos → Experiencia en estudio indie o AAA',
                'habilidades_clave' => json_encode(['Diseño de mecánicas', 'Game balancing', 'Narrativa interactiva', 'Prototyping']),
                'activo' => true,
            ],
            [
                'titulo' => 'Productor/a Musical',
                'codigo_cno' => '2831',
                'codigo_esco' => '2652.2',
                'sector' => 'Arte, Diseño y Creatividad',
                'familia_profesional' => 'Arte Musical',
                'riasec_r' => 0.15,
                'riasec_i' => 0.15,
                'riasec_a' => 0.45,
                'riasec_s' => 0.05,
                'riasec_e' => 0.15,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Dirige y supervisa la grabación, mezcla y masterización de música en estudios o home studios.',
                'salidas_profesionales' => json_encode(['Productor de estudio', 'Productor de artistas', 'Beatmaker']),
                'ruta_formativa' => 'Grado en Producción Musical o Conservatorio → Dominio de DAW (Ableton, Logic Pro) → Portfolio de producciones',
                'habilidades_clave' => json_encode(['DAW (Ableton/Logic/Pro Tools)', 'Teoría musical', 'Mezcla y mastering', 'Creatividad sonora']),
                'activo' => true,
            ],
            [
                'titulo' => 'Director/a de Arte',
                'codigo_cno' => '2166',
                'codigo_esco' => '2166.1',
                'sector' => 'Arte, Diseño y Creatividad',
                'familia_profesional' => 'Artes Gráficas',
                'riasec_r' => 0.05,
                'riasec_i' => 0.15,
                'riasec_a' => 0.45,
                'riasec_s' => 0.10,
                'riasec_e' => 0.20,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Lidera la visión creativa de campañas publicitarias, proyectos editoriales o producciones audiovisuales.',
                'salidas_profesionales' => json_encode(['Director de arte en agencia', 'Director creativo', 'Art director freelance']),
                'ruta_formativa' => 'Grado en Diseño Gráfico/Publicidad → Experiencia como diseñador → Ascenso a dirección de arte',
                'habilidades_clave' => json_encode(['Visión creativa', 'Dirección de equipo', 'Concepto y storytelling', 'Tendencias visuales']),
                'activo' => true,
            ],
            [
                'titulo' => 'Concept Artist',
                'codigo_cno' => '2852',
                'codigo_esco' => '2651.3',
                'sector' => 'Arte, Diseño y Creatividad',
                'familia_profesional' => 'Artes Gráficas',
                'riasec_r' => 0.10,
                'riasec_i' => 0.10,
                'riasec_a' => 0.60,
                'riasec_s' => 0.05,
                'riasec_e' => 0.05,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Crea diseños visuales conceptuales para videojuegos, cine, animación y publicidad antes de la producción.',
                'salidas_profesionales' => json_encode(['Concept artist en videojuegos', 'Concept artist en cine', 'Freelance concept art']),
                'ruta_formativa' => 'Grado en Bellas Artes/Ilustración → Portfolio fuerte en concept art → Experiencia en estudio',
                'habilidades_clave' => json_encode(['Dibujo digital', 'Photoshop', 'Diseño de personajes y entornos', 'Imaginación visual']),
                'activo' => true,
            ],
            [
                'titulo' => 'Editor/a de Vídeo',
                'codigo_cno' => '2654',
                'codigo_esco' => '2654.2',
                'sector' => 'Arte, Diseño y Creatividad',
                'familia_profesional' => 'Imagen y Sonido',
                'riasec_r' => 0.15,
                'riasec_i' => 0.10,
                'riasec_a' => 0.45,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Monta y edita piezas audiovisuales para cine, TV, YouTube, publicidad y redes sociales.',
                'salidas_profesionales' => json_encode(['Editor de vídeo en productora', 'Editor freelance', 'Editor de contenido para redes']),
                'ruta_formativa' => 'FP Superior en Realización Audiovisual → Dominio de Premiere/DaVinci Resolve → Reel de proyectos',
                'habilidades_clave' => json_encode(['Premiere Pro/DaVinci Resolve', 'Narrativa audiovisual', 'Color grading', 'Ritmo y timing']),
                'activo' => true,
            ],
            [
                'titulo' => 'Diseñador/a Web',
                'codigo_cno' => '2166',
                'codigo_esco' => '2166.8',
                'sector' => 'Arte, Diseño y Creatividad',
                'familia_profesional' => 'Informática y Comunicaciones',
                'riasec_r' => 0.10,
                'riasec_i' => 0.20,
                'riasec_a' => 0.45,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Diseña la interfaz visual y experiencia de usuario de sitios web, equilibrando estética y usabilidad.',
                'salidas_profesionales' => json_encode(['Web designer', 'UI designer para web', 'Diseñador freelance de landing pages']),
                'ruta_formativa' => 'FP Superior en Desarrollo Web → Especialización en diseño (Figma/Adobe XD) → Portfolio de webs',
                'habilidades_clave' => json_encode(['Figma/Adobe XD', 'HTML/CSS básico', 'Responsive design', 'Tipografía web']),
                'activo' => true,
            ],
            [
                'titulo' => 'Fotógrafo/a de Moda',
                'codigo_cno' => '2854',
                'codigo_esco' => '3431.2',
                'sector' => 'Arte, Diseño y Creatividad',
                'familia_profesional' => 'Imagen y Sonido',
                'riasec_r' => 0.20,
                'riasec_i' => 0.10,
                'riasec_a' => 0.50,
                'riasec_s' => 0.05,
                'riasec_e' => 0.10,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Captura imágenes de moda para editoriales, e-commerce, lookbooks y campañas publicitarias de marcas.',
                'salidas_profesionales' => json_encode(['Fotógrafo editorial de moda', 'Fotógrafo de producto fashion', 'Fotógrafo de pasarela']),
                'ruta_formativa' => 'FP Superior en Fotografía → Portfolio especializado en moda → Colaboraciones con diseñadores → Freelance',
                'habilidades_clave' => json_encode(['Iluminación de estudio', 'Dirección de modelos', 'Edición (Photoshop/Lightroom)', 'Estilismo visual']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // AGRICULTURA, MEDIO AMBIENTE Y SOSTENIBILIDAD: +8 profesiones
            // (De 5 → 13 total)
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Consultor/a Ambiental',
                'codigo_cno' => '2421',
                'codigo_esco' => '2133.1',
                'sector' => 'Agricultura, Medio Ambiente y Sostenibilidad',
                'familia_profesional' => 'Seguridad y Medio Ambiente',
                'riasec_r' => 0.15,
                'riasec_i' => 0.35,
                'riasec_a' => 0.05,
                'riasec_s' => 0.10,
                'riasec_e' => 0.25,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado + Máster',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Asesora a empresas en gestión ambiental, evaluación de impacto y cumplimiento normativo medioambiental.',
                'salidas_profesionales' => json_encode(['Consultor ambiental', 'Auditor ISO 14001', 'Gestor de sostenibilidad corporativa']),
                'ruta_formativa' => 'Grado en Ciencias Ambientales → Máster en Gestión Ambiental → Experiencia en consultora → Certificaciones ISO',
                'habilidades_clave' => json_encode(['Legislación ambiental', 'Evaluación de impacto', 'Sistemas de gestión ambiental', 'Reporting de sostenibilidad']),
                'activo' => true,
            ],
            [
                'titulo' => 'Ingeniero/a en Energías Renovables',
                'codigo_cno' => '2149',
                'codigo_esco' => '2149.1',
                'sector' => 'Agricultura, Medio Ambiente y Sostenibilidad',
                'familia_profesional' => 'Energía y Agua',
                'riasec_r' => 0.30,
                'riasec_i' => 0.35,
                'riasec_a' => 0.05,
                'riasec_s' => 0.05,
                'riasec_e' => 0.15,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'Grado + Máster',
                'nivel_salarial' => 'Alto',
                'tipo_profesion' => 'emergente',
                'descripcion_corta' => 'Diseña, implementa y optimiza sistemas de energía solar, eólica, biomasa e hidroeléctrica.',
                'salidas_profesionales' => json_encode(['Ingeniero de parques eólicos', 'Ingeniero fotovoltaico', 'Project manager de energías renovables']),
                'ruta_formativa' => 'Grado en Ingeniería de la Energía/Industrial → Máster en Energías Renovables → Proyectos de instalaciones',
                'habilidades_clave' => json_encode(['Energía solar/eólica', 'Diseño de instalaciones', 'Normativa eléctrica', 'Viabilidad económica']),
                'activo' => true,
            ],
            [
                'titulo' => 'Educador/a Ambiental',
                'codigo_cno' => '2359',
                'codigo_esco' => '2359.3',
                'sector' => 'Agricultura, Medio Ambiente y Sostenibilidad',
                'familia_profesional' => 'Servicios Socioculturales y a la Comunidad',
                'riasec_r' => 0.10,
                'riasec_i' => 0.20,
                'riasec_a' => 0.15,
                'riasec_s' => 0.40,
                'riasec_e' => 0.10,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Diseña e imparte programas educativos para sensibilizar sobre conservación y sostenibilidad ambiental.',
                'salidas_profesionales' => json_encode(['Educador en parques naturales', 'Monitor de actividades ambientales', 'Técnico en ONGs ecologistas']),
                'ruta_formativa' => 'Grado en Ciencias Ambientales/Educación → Máster en Educación Ambiental → Experiencia con grupos',
                'habilidades_clave' => json_encode(['Didáctica ambiental', 'Comunicación', 'Dinámicas de grupo', 'Conocimiento de ecosistemas']),
                'activo' => true,
            ],
            [
                'titulo' => 'Gestor/a de Residuos',
                'codigo_cno' => '2421',
                'codigo_esco' => '2133.2',
                'sector' => 'Agricultura, Medio Ambiente y Sostenibilidad',
                'familia_profesional' => 'Seguridad y Medio Ambiente',
                'riasec_r' => 0.25,
                'riasec_i' => 0.25,
                'riasec_a' => 0.00,
                'riasec_s' => 0.10,
                'riasec_e' => 0.25,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Planifica y supervisa la gestión integral de residuos urbanos e industriales, promoviendo economía circular.',
                'salidas_profesionales' => json_encode(['Gestor de residuos municipales', 'Técnico en plantas de reciclaje', 'Consultor en economía circular']),
                'ruta_formativa' => 'Grado en Ciencias Ambientales/Ingeniería Química → Máster en Gestión de Residuos → Experiencia en sector',
                'habilidades_clave' => json_encode(['Legislación de residuos', 'Procesos de reciclaje', 'Economía circular', 'Gestión de plantas']),
                'activo' => true,
            ],
            [
                'titulo' => 'Técnico/a en Agricultura Ecológica',
                'codigo_cno' => '6111',
                'codigo_esco' => '6111.1',
                'sector' => 'Agricultura, Medio Ambiente y Sostenibilidad',
                'familia_profesional' => 'Agraria',
                'riasec_r' => 0.45,
                'riasec_i' => 0.15,
                'riasec_a' => 0.05,
                'riasec_s' => 0.10,
                'riasec_e' => 0.15,
                'riasec_c' => 0.10,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Gestiona cultivos ecológicos sin pesticidas ni fertilizantes sintéticos, promoviendo biodiversidad.',
                'salidas_profesionales' => json_encode(['Agricultor ecológico', 'Técnico en cooperativas ecológicas', 'Asesor en conversión ecológica']),
                'ruta_formativa' => 'FP Superior en Paisajismo y Medio Rural o Agricultura Ecológica → Certificación ecológica → Explotación propia',
                'habilidades_clave' => json_encode(['Cultivo ecológico', 'Control biológico de plagas', 'Normativa eco', 'Trabajo físico al aire libre']),
                'activo' => true,
            ],
            [
                'titulo' => 'Especialista en Permacultura',
                'codigo_cno' => '6111',
                'codigo_esco' => '6111.2',
                'sector' => 'Agricultura, Medio Ambiente y Sostenibilidad',
                'familia_profesional' => 'Agraria',
                'riasec_r' => 0.40,
                'riasec_i' => 0.20,
                'riasec_a' => 0.10,
                'riasec_s' => 0.15,
                'riasec_e' => 0.10,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'emergente',
                'descripcion_corta' => 'Diseña sistemas agrícolas sostenibles basados en patrones naturales, integrando cultivos, agua y energía.',
                'salidas_profesionales' => json_encode(['Diseñador de permacultura', 'Consultor en agroecología', 'Educador en permacultura']),
                'ruta_formativa' => 'FP Agraria o Forestal → Certificado de Diseño en Permacultura (PDC) → Proyectos prácticos → Educación o consultora',
                'habilidades_clave' => json_encode(['Diseño de sistemas', 'Agroecología', 'Gestión del agua', 'Pensamiento sistémico']),
                'activo' => true,
            ],

            // ══════════════════════════════════════════════
            // OTRAS PROFESIONES ESTRATÉGICAS: +7 profesiones
            // Distribuidas en sectores con menor representación
            // ══════════════════════════════════════════════
            [
                'titulo' => 'Entrenador/a Personal',
                'codigo_cno' => '3422',
                'codigo_esco' => '3422.1',
                'sector' => 'Deporte y Actividad Física',
                'familia_profesional' => 'Actividades Físicas y Deportivas',
                'riasec_r' => 0.30,
                'riasec_i' => 0.10,
                'riasec_a' => 0.05,
                'riasec_s' => 0.40,
                'riasec_e' => 0.10,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'en_crecimiento',
                'descripcion_corta' => 'Diseña y supervisa programas de entrenamiento físico personalizados para mejorar condición física y salud.',
                'salidas_profesionales' => json_encode(['Entrenador personal en gimnasio', 'Entrenador online', 'Preparador físico deportivo']),
                'ruta_formativa' => 'FP Superior en Acondicionamiento Físico → Certificaciones (NSCA, ACE) → Experiencia con clientes',
                'habilidades_clave' => json_encode(['Fisiología del ejercicio', 'Programación de entrenamientos', 'Motivación', 'Nutrición deportiva básica']),
                'activo' => true,
            ],
            [
                'titulo' => 'Chef / Jefe de Cocina',
                'codigo_cno' => '5120',
                'codigo_esco' => '5120.1',
                'sector' => 'Turismo, Hostelería y Gastronomía',
                'familia_profesional' => 'Hostelería y Turismo',
                'riasec_r' => 0.25,
                'riasec_i' => 0.10,
                'riasec_a' => 0.35,
                'riasec_s' => 0.05,
                'riasec_e' => 0.20,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Crea platos, gestiona cocinas de restaurantes y lidera equipos culinarios con creatividad y excelencia.',
                'salidas_profesionales' => json_encode(['Chef ejecutivo', 'Jefe de cocina en hotel', 'Chef privado', 'Restaurante propio']),
                'ruta_formativa' => 'FP Superior en Dirección de Cocina → Experiencia en restaurantes → Especialización (cocina de autor, pastelería)',
                'habilidades_clave' => json_encode(['Técnica culinaria', 'Creatividad gastronómica', 'Gestión de cocina', 'Liderazgo']),
                'activo' => true,
            ],
            [
                'titulo' => 'Guía Turístico/a',
                'codigo_cno' => '5113',
                'codigo_esco' => '5113.1',
                'sector' => 'Turismo, Hostelería y Gastronomía',
                'familia_profesional' => 'Hostelería y Turismo',
                'riasec_r' => 0.10,
                'riasec_i' => 0.20,
                'riasec_a' => 0.15,
                'riasec_s' => 0.40,
                'riasec_e' => 0.10,
                'riasec_c' => 0.05,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio-bajo',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Acompaña y explica patrimonio histórico, cultural y natural a turistas nacionales e internacionales.',
                'salidas_profesionales' => json_encode(['Guía oficial de turismo', 'Guía de museos', 'Guía de naturaleza', 'Guía freelance']),
                'ruta_formativa' => 'FP Superior en Guía, Información y Asistencias Turísticas → Habilitación oficial por CCAA → Idiomas',
                'habilidades_clave' => json_encode(['Conocimiento histórico-cultural', 'Idiomas', 'Oratoria', 'Trato con el público']),
                'activo' => true,
            ],
            [
                'titulo' => 'Conductor/a de Transporte de Mercancías',
                'codigo_cno' => '8331',
                'codigo_esco' => '8332.1',
                'sector' => 'Logística y Transporte',
                'familia_profesional' => 'Transporte y Mantenimiento de Vehículos',
                'riasec_r' => 0.50,
                'riasec_i' => 0.05,
                'riasec_a' => 0.00,
                'riasec_s' => 0.05,
                'riasec_e' => 0.05,
                'riasec_c' => 0.35,
                'nivel_formacion' => 'FP Medio',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Transporta mercancías por carretera en camiones, cumpliendo normativa de tráfico y tiempos de conducción.',
                'salidas_profesionales' => json_encode(['Conductor de camión', 'Conductor de reparto', 'Conductor internacional']),
                'ruta_formativa' => 'Carnet C+E (camión articulado) → CAP (Certificado Aptitud Profesional) → Experiencia en empresas logísticas',
                'habilidades_clave' => json_encode(['Conducción profesional', 'Normativa de transporte', 'Responsabilidad', 'Resistencia física']),
                'activo' => true,
            ],
            [
                'titulo' => 'Gestor/a de Recursos Humanos',
                'codigo_cno' => '2422',
                'codigo_esco' => '2423.1',
                'sector' => 'Administración Pública y Gestión',
                'familia_profesional' => 'Administración y Gestión',
                'riasec_r' => 0.00,
                'riasec_i' => 0.15,
                'riasec_a' => 0.05,
                'riasec_s' => 0.35,
                'riasec_e' => 0.30,
                'riasec_c' => 0.15,
                'nivel_formacion' => 'Grado Universitario',
                'nivel_salarial' => 'Medio-alto',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Gestiona selección, formación, desarrollo y bienestar de los empleados de una organización.',
                'salidas_profesionales' => json_encode(['HR Manager', 'Técnico de selección', 'Responsable de formación', 'HR Business Partner']),
                'ruta_formativa' => 'Grado en Relaciones Laborales/Psicología/ADE → Máster en RRHH → Experiencia en departamento de RRHH',
                'habilidades_clave' => json_encode(['Selección de personal', 'Gestión del talento', 'Legislación laboral', 'Comunicación interpersonal']),
                'activo' => true,
            ],
            [
                'titulo' => 'Técnico/a de PRL (Prevención de Riesgos Laborales)',
                'codigo_cno' => '2422',
                'codigo_esco' => '2263.1',
                'sector' => 'Administración Pública y Gestión',
                'familia_profesional' => 'Seguridad y Medio Ambiente',
                'riasec_r' => 0.20,
                'riasec_i' => 0.25,
                'riasec_a' => 0.00,
                'riasec_s' => 0.15,
                'riasec_e' => 0.10,
                'riasec_c' => 0.30,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Evalúa riesgos laborales, propone medidas preventivas y vela por la seguridad y salud en el trabajo.',
                'salidas_profesionales' => json_encode(['Técnico PRL en empresa', 'Coordinador de seguridad en obra', 'Auditor de PRL']),
                'ruta_formativa' => 'FP Superior en PRL → Máster PRL (nivel superior, 3 especialidades) → Experiencia en empresa',
                'habilidades_clave' => json_encode(['Legislación PRL', 'Evaluación de riesgos', 'Ergonomía', 'Formación en seguridad']),
                'activo' => true,
            ],
            [
                'titulo' => 'Administrativo/a Especializado',
                'codigo_cno' => '4110',
                'codigo_esco' => '4110.1',
                'sector' => 'Administración Pública y Gestión',
                'familia_profesional' => 'Administración y Gestión',
                'riasec_r' => 0.00,
                'riasec_i' => 0.10,
                'riasec_a' => 0.00,
                'riasec_s' => 0.10,
                'riasec_e' => 0.15,
                'riasec_c' => 0.65,
                'nivel_formacion' => 'FP Superior',
                'nivel_salarial' => 'Medio',
                'tipo_profesion' => 'tradicional',
                'descripcion_corta' => 'Gestiona documentación, trámites administrativos, facturación y atención en oficinas públicas y privadas.',
                'salidas_profesionales' => json_encode(['Administrativo en empresa', 'Administrativo en ayuntamiento (oposición)', 'Asistente de dirección']),
                'ruta_formativa' => 'FP Superior en Administración y Finanzas → Oposiciones (función pública) o sector privado → Especialización sectorial',
                'habilidades_clave' => json_encode(['Ofimática avanzada', 'Gestión documental', 'Atención al público', 'Organización']),
                'activo' => true,
            ],
        ];
    }
}
